<?xml version="1.0" encoding="utf-8"?><Database Name="MvParadisePaintball" Class="UberstrikeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.AllTimeTotalRanking" Member="AllTimeTotalRankings">
    <Type Name="AllTimeTotalRanking">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ranknum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Splats" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Splatted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KDRatio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Shots" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberSince" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NbPoints" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WeeklyTotalRanking" Member="WeeklyTotalRankings">
    <Type Name="WeeklyTotalRanking">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ranknum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Splats" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Splatted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalSplats" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalSplatted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KDRatio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="KDRatioTotal" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Shots" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShotsTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HitsTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberSince" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NbPoints" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WeekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NbPointsTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RanknumTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationVersions" Member="ApplicationVersions">
    <Type Name="ApplicationVersion">
      <Column Name="ApplicationVersionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="WebPlayerFileName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Channel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModificationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WarnPlayer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhotonClusterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PhotonsGroup_ApplicationVersion" Member="PhotonsGroup" ThisKey="PhotonClusterId" OtherKey="PhotonsGroupID" Type="PhotonsGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClientDownloadStats" Member="ClientDownloadStats">
    <Type Name="ClientDownloadStat">
      <Column Name="ClientDownloadStatsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DownloadDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Channel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DownloadCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cyworld" Member="Cyworlds">
    <Type Name="Cyworld">
      <Column Name="CyworldId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_Cyworld" Member="User" ThisKey="UserId" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CyworldReferrers" Member="CyworldReferrers">
    <Type Name="CyworldReferrer">
      <Column Name="CyworldReferrerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CyworldId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Referrer" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="ReferrerPartnerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DailyRanking" Member="DailyRankings">
    <Type Name="DailyRanking">
      <Column Name="DailyRankingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DailyRankingIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClanTag" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Cmid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Kills" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalKills" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deaths" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalDeaths" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shots" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalShots" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Hits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalHits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalXP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LevelsGained" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsBanned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FacebookReferrers" Member="FacebookReferrers">
    <Type Name="FacebookReferrer">
      <Column Name="FacebookReferrerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FacebookID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Referrer" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="ReferrerPartnerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="Cmid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ItemFunctionalConfig" Member="ItemFunctionalConfigs">
    <Type Name="ItemFunctionalConfig">
      <Column Name="ItemFunctionalConfigId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LevelRequired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ItemGearConfig" Member="ItemGearConfigs">
    <Type Name="ItemGearConfig">
      <Column Name="ItemGearConfigId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LevelRequired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArmorPoints" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArmorAbsorptionPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArmorWeight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ItemsAttributedOnTutorial" Member="ItemsAttributedOnTutorials">
    <Type Name="ItemsAttributedOnTutorial">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ItemSpecialConfig" Member="ItemSpecialConfigs">
    <Type Name="ItemSpecialConfig">
      <Column Name="ItemSpecialConfigId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LevelRequired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ItemWeaponConfig" Member="ItemWeaponConfigs">
    <Type Name="ItemWeaponConfig">
      <Column Name="ItemWeaponConfigId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LevelRequired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DamageKnockback" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DamagePerProjectile" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RateOfFire" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccuracySpread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecoilKickback" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartAmmo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxAmmo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MissileTimeToDetonate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MissileForceImpulse" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MissileBounciness" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SplashRadius" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectilesPerShot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectileSpeed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecoilMovement" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ItemWeaponModConfig" Member="ItemWeaponModConfigs">
    <Type Name="ItemWeaponModConfig">
      <Column Name="ItemWeaponModConfigId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LevelRequired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LiveFeeds" Member="LiveFeeds">
    <Type Name="LiveFeed">
      <Column Name="LiveFeedId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(140) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Loadouts" Member="Loadouts">
    <Type Name="Loadout">
      <Column Name="LoadoutId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cmid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon1Mod1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon1Mod2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon1Mod3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon2Mod1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon2Mod2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon2Mod3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon3Mod1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon3Mod2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weapon3Mod3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeleeWeapon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Backpack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Webbing" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpperBody" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LowerBody" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Head" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Face" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gloves" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Boots" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuickItem1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuickItem2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuickItem3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FunctionalItem1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FunctionalItem2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FunctionalItem3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SkinColor" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MapUsage" Member="MapUsages">
    <Type Name="MapUsage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MapId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GameModeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeLimit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayerLimit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayersTotal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayersCompleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MySpace" Member="MySpaces">
    <Type Name="MySpace">
      <Column Name="MySpaceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_MySpace" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MySpaceReferrers" Member="MySpaceReferrers">
    <Type Name="MySpaceReferrer">
      <Column Name="MySpaceReferrerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MySpaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Referrer" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="ReferrerPartnerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhotonServers" Member="PhotonServers">
    <Type Name="PhotonServer">
      <Column Name="PhotonServerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Port" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsageType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhotonsGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Member="MinLatency" Type="System.Int32" CanBeNull="false" />
      <Association Name="PhotonsGroup_PhotonServer" Member="PhotonsGroup" ThisKey="PhotonsGroupID" OtherKey="PhotonsGroupID" Type="PhotonsGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhotonsGroups" Member="PhotonsGroups">
    <Type Name="PhotonsGroup">
      <Column Name="PhotonsGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModificationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="PhotonsGroup_ApplicationVersion" Member="ApplicationVersions" ThisKey="PhotonsGroupID" OtherKey="PhotonClusterId" Type="ApplicationVersion" />
      <Association Name="PhotonsGroup_PhotonServer" Member="PhotonServers" ThisKey="PhotonsGroupID" OtherKey="PhotonsGroupID" Type="PhotonServer" />
    </Type>
  </Table>
  <Table Name="dbo.PlayerLevelCaps" Member="PlayerLevelCaps">
    <Type Name="PlayerLevelCap">
      <Column Name="PlayerLevelCapId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XPRequired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PlayerXPEvents" Member="PlayerXPEvents">
    <Type Name="PlayerXPEvent">
      <Column Name="PlayerXPEventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="XPMultiplier" Type="System.Decimal" DbType="Decimal(6,3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PortalReferrers" Member="PortalReferrers">
    <Type Name="PortalReferrer">
      <Column Name="PortalReferrerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Referrer" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="ReferrerPartnerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cmid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PromotionContent" Member="PromotionContents">
    <Type Name="PromotionContent">
      <Column Name="PromotionContentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsPermanent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PromotionContentElements" Member="PromotionContentElements">
    <Type Name="PromotionContentElement">
      <Column Name="PromotionContentElementId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChannelType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChannelLocation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="FilenameTitle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PromotionContentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnchorLink" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReferrerSource" Member="ReferrerSources">
    <Type Name="ReferrerSource">
      <Column Name="ReferrerSourceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParameterName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ParameterValue" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChannelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SecondParameterName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SecondParameterValue" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ReferrerPartnerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TmpRanking" Member="TmpRankings">
    <Type Name="TmpRanking">
      <Column Name="RankIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cmid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TutorialSteps" Member="TutorialSteps">
    <Type Name="TutorialStep">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cmid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StepId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StepDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserInstall" Member="UserInstalls">
    <Type Name="UserInstall">
      <Column Name="UserInstallId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrackingId" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChannelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReferrerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsJavaInstallEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OsName" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ip" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="OsVersion" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BrowserName" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="BrowserVersion" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="UserAgent" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="HasUnity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UserInstall_UserInstallStep" Member="UserInstallSteps" ThisKey="UserInstallId" OtherKey="UserInstallId" Type="UserInstallStep" />
    </Type>
  </Table>
  <Table Name="dbo.UserInstallStep" Member="UserInstallSteps">
    <Type Name="UserInstallStep">
      <Column Name="InstallStepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserInstallId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StepType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="StepDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserInstall_UserInstallStep" Member="UserInstall" ThisKey="UserInstallId" OtherKey="UserInstallId" Type="UserInstall" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Splats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Splatted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shots" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Hits" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeleeTotalSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HandgunTotalSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineGunTotalSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShotgunTotalSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SniperTotalSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SplattergunTotalSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CannonTotalSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LauncherTotalSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostHeadshots" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostNutshots" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostConsecutiveSnipes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostXPEarned" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostDamageDealt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostDamageReceived" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostArmorPickedUp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostHealthPickedUp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostMeleeSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostHandgunSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostMachinegunSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostShotgunSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostSniperSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostSplattergunSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostCannonSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MostLauncherSplats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeSpentInGame" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeleeTotalShotsFired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeleeTotalShotsHit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeleeTotalDamageDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HandgunTotalShotsFired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HandgunTotalShotsHit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HandgunTotalDamageDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineGunTotalShotsFired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineGunTotalShotsHit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MachineGunTotalDamageDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShotgunTotalShotsFired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShotgunTotalShotsHit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShotgunTotalDamageDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SniperTotalShotsFired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SniperTotalShotsHit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SniperTotalDamageDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SplattergunTotalShotsFired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SplattergunTotalShotsHit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SplattergunTotalDamageDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CannonTotalShotsFired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CannonTotalShotsHit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CannonTotalDamageDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LauncherTotalShotsHit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LauncherTotalDamageDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Headshots" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nutshots" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LauncherTotalShotsFired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Cyworld" Member="Cyworlds" ThisKey="UserID" OtherKey="UserId" Type="Cyworld" />
      <Association Name="User_MySpace" Member="MySpaces" ThisKey="UserID" OtherKey="UserID" Type="MySpace" />
    </Type>
  </Table>
  <Table Name="dbo.KongregateReferrers" Member="KongregateReferrers">
    <Type Name="KongregateReferrer">
      <Column Name="KongregateReferrerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KongregateId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Referrer" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="ReferrerPartnerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="Cmid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MapVersions" Member="MapVersions">
    <Type Name="MapVersion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MapId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AppVersion" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MapType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WeeklySpecials" Member="WeeklySpecials">
    <Type Name="WeeklySpecial">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PopupTitle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PopupText" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Maps" Member="Maps">
    <Type Name="Map">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MapId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AppVersion" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SceneName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InUse" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBlueBox" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RecommendedItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemQuickUseConfig" Member="ItemQuickUseConfigs">
    <Type Name="ItemQuickUseConfig">
      <Column Name="ItemQuickUseConfigId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LevelRequired" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsesPerLife" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsesPerRound" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsesPerGame" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CoolDownTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WarmUpTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BehaviourType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.Paradise_FacebookTopRank_S" Method="Paradise_FacebookTopRank_S" IsComposable="true">
    <Return Type="object" />
  </Function>
  <Function Name="dbo.Paradise_Propagate_Name" Method="Paradise_Propagate_Name">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Cmid" Parameter="cmid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Paradise_UserRank_Cmid_S" Method="Paradise_UserRank_Cmid_S" IsComposable="true">
    <Parameter Name="cmid" Type="System.Int32" DbType="Int" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.UberStrike_Propagate_Tags" Method="UberStrike_Propagate_Tags">
    <Parameter Name="Tag" Parameter="tag" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Cmids" Parameter="cmids" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Paradise_Propagate_TagName" Method="Paradise_Propagate_TagName">
    <Parameter Name="TagName" Parameter="tagName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Cmid" Parameter="cmid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>