//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.237.
// 
#pragma warning disable 1591

namespace Cmune.DataCenter.Forum.Business.PhpBBSync {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="phpBBSyncBinding", Namespace="http://forum.uberstrike.com/webServices/")]
    public partial class phpBBSync : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ws_clean_stringOperationCompleted;
        
        private System.Threading.SendOrPostCallback ws_clean_string_testOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public phpBBSync() {
            this.Url = global::Cmune.DataCenter.Forum.Business.Properties.Settings.Default.ForumManager_PhpBBSync_phpBBSync;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ws_clean_stringCompletedEventHandler ws_clean_stringCompleted;
        
        /// <remarks/>
        public event ws_clean_string_testCompletedEventHandler ws_clean_string_testCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://forum.uberstrike.com/webServices/#ws_clean_string", RequestNamespace="http://forum.uberstrike.com/webServices/", ResponseNamespace="http://forum.uberstrike.com/webServices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("clean_string")]
        public string ws_clean_string(string text, string secret_key) {
            object[] results = this.Invoke("ws_clean_string", new object[] {
                        text,
                        secret_key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_clean_stringAsync(string text, string secret_key) {
            this.ws_clean_stringAsync(text, secret_key, null);
        }
        
        /// <remarks/>
        public void ws_clean_stringAsync(string text, string secret_key, object userState) {
            if ((this.ws_clean_stringOperationCompleted == null)) {
                this.ws_clean_stringOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_clean_stringOperationCompleted);
            }
            this.InvokeAsync("ws_clean_string", new object[] {
                        text,
                        secret_key}, this.ws_clean_stringOperationCompleted, userState);
        }
        
        private void Onws_clean_stringOperationCompleted(object arg) {
            if ((this.ws_clean_stringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_clean_stringCompleted(this, new ws_clean_stringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://forum.uberstrike.com/webServices/#ws_clean_string_test", RequestNamespace="http://forum.uberstrike.com/webServices/", ResponseNamespace="http://forum.uberstrike.com/webServices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("clean_string_test")]
        public string ws_clean_string_test(string text, string secret_key) {
            object[] results = this.Invoke("ws_clean_string_test", new object[] {
                        text,
                        secret_key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ws_clean_string_testAsync(string text, string secret_key) {
            this.ws_clean_string_testAsync(text, secret_key, null);
        }
        
        /// <remarks/>
        public void ws_clean_string_testAsync(string text, string secret_key, object userState) {
            if ((this.ws_clean_string_testOperationCompleted == null)) {
                this.ws_clean_string_testOperationCompleted = new System.Threading.SendOrPostCallback(this.Onws_clean_string_testOperationCompleted);
            }
            this.InvokeAsync("ws_clean_string_test", new object[] {
                        text,
                        secret_key}, this.ws_clean_string_testOperationCompleted, userState);
        }
        
        private void Onws_clean_string_testOperationCompleted(object arg) {
            if ((this.ws_clean_string_testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ws_clean_string_testCompleted(this, new ws_clean_string_testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ws_clean_stringCompletedEventHandler(object sender, ws_clean_stringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_clean_stringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_clean_stringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ws_clean_string_testCompletedEventHandler(object sender, ws_clean_string_testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ws_clean_string_testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ws_clean_string_testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591