#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmune.Instrumentation.Monitoring.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CmuneMonitoring")]
	public partial class CmuneMonitoringDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertManagedServerMonitoring(ManagedServerMonitoring instance);
    partial void UpdateManagedServerMonitoring(ManagedServerMonitoring instance);
    partial void DeleteManagedServerMonitoring(ManagedServerMonitoring instance);
    partial void InsertUnityException(UnityException instance);
    partial void UpdateUnityException(UnityException instance);
    partial void DeleteUnityException(UnityException instance);
    partial void InsertManagedServer(ManagedServer instance);
    partial void UpdateManagedServer(ManagedServer instance);
    partial void DeleteManagedServer(ManagedServer instance);
    partial void InsertPhotonMonitoringDetail(PhotonMonitoringDetail instance);
    partial void UpdatePhotonMonitoringDetail(PhotonMonitoringDetail instance);
    partial void DeletePhotonMonitoringDetail(PhotonMonitoringDetail instance);
    partial void InsertPhotonMonitoringInstance(PhotonMonitoringInstance instance);
    partial void UpdatePhotonMonitoringInstance(PhotonMonitoringInstance instance);
    partial void DeletePhotonMonitoringInstance(PhotonMonitoringInstance instance);
    #endregion
		
		public CmuneMonitoringDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CmuneMonitoringDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CmuneMonitoringDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CmuneMonitoringDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ManagedServerMonitoring> ManagedServerMonitorings
		{
			get
			{
				return this.GetTable<ManagedServerMonitoring>();
			}
		}
		
		public System.Data.Linq.Table<UnityException> UnityExceptions
		{
			get
			{
				return this.GetTable<UnityException>();
			}
		}
		
		public System.Data.Linq.Table<ManagedServer> ManagedServers
		{
			get
			{
				return this.GetTable<ManagedServer>();
			}
		}
		
		public System.Data.Linq.Table<PhotonMonitoringDetail> PhotonMonitoringDetails
		{
			get
			{
				return this.GetTable<PhotonMonitoringDetail>();
			}
		}
		
		public System.Data.Linq.Table<PhotonMonitoringInstance> PhotonMonitoringInstances
		{
			get
			{
				return this.GetTable<PhotonMonitoringInstance>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManagedServerMonitoring")]
	public partial class ManagedServerMonitoring : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ManagedServerMonitoringId;
		
		private int _CPUUsage;
		
		private int _RamUsage;
		
		private System.DateTime _ReportTime;
		
		private decimal _BandwidthUsage;
		
		private decimal _DiskUsage;
		
		private int _ManagedServerId;
		
		private EntityRef<ManagedServer> _ManagedServer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManagedServerMonitoringIdChanging(int value);
    partial void OnManagedServerMonitoringIdChanged();
    partial void OnCPUUsageChanging(int value);
    partial void OnCPUUsageChanged();
    partial void OnRamUsageChanging(int value);
    partial void OnRamUsageChanged();
    partial void OnReportTimeChanging(System.DateTime value);
    partial void OnReportTimeChanged();
    partial void OnBandwidthUsageChanging(decimal value);
    partial void OnBandwidthUsageChanged();
    partial void OnDiskUsageChanging(decimal value);
    partial void OnDiskUsageChanged();
    partial void OnManagedServerIdChanging(int value);
    partial void OnManagedServerIdChanged();
    #endregion
		
		public ManagedServerMonitoring()
		{
			this._ManagedServer = default(EntityRef<ManagedServer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedServerMonitoringId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ManagedServerMonitoringId
		{
			get
			{
				return this._ManagedServerMonitoringId;
			}
			set
			{
				if ((this._ManagedServerMonitoringId != value))
				{
					this.OnManagedServerMonitoringIdChanging(value);
					this.SendPropertyChanging();
					this._ManagedServerMonitoringId = value;
					this.SendPropertyChanged("ManagedServerMonitoringId");
					this.OnManagedServerMonitoringIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPUUsage", DbType="Int NOT NULL")]
		public int CPUUsage
		{
			get
			{
				return this._CPUUsage;
			}
			set
			{
				if ((this._CPUUsage != value))
				{
					this.OnCPUUsageChanging(value);
					this.SendPropertyChanging();
					this._CPUUsage = value;
					this.SendPropertyChanged("CPUUsage");
					this.OnCPUUsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RamUsage", DbType="Int NOT NULL")]
		public int RamUsage
		{
			get
			{
				return this._RamUsage;
			}
			set
			{
				if ((this._RamUsage != value))
				{
					this.OnRamUsageChanging(value);
					this.SendPropertyChanging();
					this._RamUsage = value;
					this.SendPropertyChanged("RamUsage");
					this.OnRamUsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportTime", DbType="DateTime NOT NULL")]
		public System.DateTime ReportTime
		{
			get
			{
				return this._ReportTime;
			}
			set
			{
				if ((this._ReportTime != value))
				{
					this.OnReportTimeChanging(value);
					this.SendPropertyChanging();
					this._ReportTime = value;
					this.SendPropertyChanged("ReportTime");
					this.OnReportTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BandwidthUsage", DbType="Decimal(18,2) NOT NULL")]
		public decimal BandwidthUsage
		{
			get
			{
				return this._BandwidthUsage;
			}
			set
			{
				if ((this._BandwidthUsage != value))
				{
					this.OnBandwidthUsageChanging(value);
					this.SendPropertyChanging();
					this._BandwidthUsage = value;
					this.SendPropertyChanged("BandwidthUsage");
					this.OnBandwidthUsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiskUsage", DbType="Decimal(18,2) NOT NULL")]
		public decimal DiskUsage
		{
			get
			{
				return this._DiskUsage;
			}
			set
			{
				if ((this._DiskUsage != value))
				{
					this.OnDiskUsageChanging(value);
					this.SendPropertyChanging();
					this._DiskUsage = value;
					this.SendPropertyChanged("DiskUsage");
					this.OnDiskUsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedServerId", DbType="Int NOT NULL")]
		public int ManagedServerId
		{
			get
			{
				return this._ManagedServerId;
			}
			set
			{
				if ((this._ManagedServerId != value))
				{
					if (this._ManagedServer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManagedServerIdChanging(value);
					this.SendPropertyChanging();
					this._ManagedServerId = value;
					this.SendPropertyChanged("ManagedServerId");
					this.OnManagedServerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManagedServer_ManagedServerMonitoring", Storage="_ManagedServer", ThisKey="ManagedServerId", OtherKey="ManagedServerID", IsForeignKey=true)]
		public ManagedServer ManagedServer
		{
			get
			{
				return this._ManagedServer.Entity;
			}
			set
			{
				ManagedServer previousValue = this._ManagedServer.Entity;
				if (((previousValue != value) 
							|| (this._ManagedServer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ManagedServer.Entity = null;
						previousValue.ManagedServerMonitorings.Remove(this);
					}
					this._ManagedServer.Entity = value;
					if ((value != null))
					{
						value.ManagedServerMonitorings.Add(this);
						this._ManagedServerId = value.ManagedServerID;
					}
					else
					{
						this._ManagedServerId = default(int);
					}
					this.SendPropertyChanged("ManagedServer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnityExceptions")]
	public partial class UnityException : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UnityExceptionId;
		
		private string _ExceptionType;
		
		private string _ExceptionMessage;
		
		private int _Cmid;
		
		private int _Channel;
		
		private int _Build;
		
		private System.DateTime _ExceptionTime;
		
		private string _Stacktrace;
		
		private string _StacktraceHash;
		
		private string _FaultiveFunction;
		
		private string _ExceptionData;
		
		private string _BuildNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUnityExceptionIdChanging(int value);
    partial void OnUnityExceptionIdChanged();
    partial void OnExceptionTypeChanging(string value);
    partial void OnExceptionTypeChanged();
    partial void OnExceptionMessageChanging(string value);
    partial void OnExceptionMessageChanged();
    partial void OnCmidChanging(int value);
    partial void OnCmidChanged();
    partial void OnChannelChanging(int value);
    partial void OnChannelChanged();
    partial void OnBuildChanging(int value);
    partial void OnBuildChanged();
    partial void OnExceptionTimeChanging(System.DateTime value);
    partial void OnExceptionTimeChanged();
    partial void OnStacktraceChanging(string value);
    partial void OnStacktraceChanged();
    partial void OnStacktraceHashChanging(string value);
    partial void OnStacktraceHashChanged();
    partial void OnFaultiveFunctionChanging(string value);
    partial void OnFaultiveFunctionChanged();
    partial void OnExceptionDataChanging(string value);
    partial void OnExceptionDataChanged();
    partial void OnBuildNumberChanging(string value);
    partial void OnBuildNumberChanged();
    #endregion
		
		public UnityException()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnityExceptionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UnityExceptionId
		{
			get
			{
				return this._UnityExceptionId;
			}
			set
			{
				if ((this._UnityExceptionId != value))
				{
					this.OnUnityExceptionIdChanging(value);
					this.SendPropertyChanging();
					this._UnityExceptionId = value;
					this.SendPropertyChanged("UnityExceptionId");
					this.OnUnityExceptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ExceptionType
		{
			get
			{
				return this._ExceptionType;
			}
			set
			{
				if ((this._ExceptionType != value))
				{
					this.OnExceptionTypeChanging(value);
					this.SendPropertyChanging();
					this._ExceptionType = value;
					this.SendPropertyChanged("ExceptionType");
					this.OnExceptionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionMessage", DbType="NVarChar(600) NOT NULL", CanBeNull=false)]
		public string ExceptionMessage
		{
			get
			{
				return this._ExceptionMessage;
			}
			set
			{
				if ((this._ExceptionMessage != value))
				{
					this.OnExceptionMessageChanging(value);
					this.SendPropertyChanging();
					this._ExceptionMessage = value;
					this.SendPropertyChanged("ExceptionMessage");
					this.OnExceptionMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cmid", DbType="Int NOT NULL")]
		public int Cmid
		{
			get
			{
				return this._Cmid;
			}
			set
			{
				if ((this._Cmid != value))
				{
					this.OnCmidChanging(value);
					this.SendPropertyChanging();
					this._Cmid = value;
					this.SendPropertyChanged("Cmid");
					this.OnCmidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Channel", DbType="Int NOT NULL")]
		public int Channel
		{
			get
			{
				return this._Channel;
			}
			set
			{
				if ((this._Channel != value))
				{
					this.OnChannelChanging(value);
					this.SendPropertyChanging();
					this._Channel = value;
					this.SendPropertyChanged("Channel");
					this.OnChannelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Build", DbType="Int NOT NULL")]
		public int Build
		{
			get
			{
				return this._Build;
			}
			set
			{
				if ((this._Build != value))
				{
					this.OnBuildChanging(value);
					this.SendPropertyChanging();
					this._Build = value;
					this.SendPropertyChanged("Build");
					this.OnBuildChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionTime", DbType="DateTime NOT NULL")]
		public System.DateTime ExceptionTime
		{
			get
			{
				return this._ExceptionTime;
			}
			set
			{
				if ((this._ExceptionTime != value))
				{
					this.OnExceptionTimeChanging(value);
					this.SendPropertyChanging();
					this._ExceptionTime = value;
					this.SendPropertyChanged("ExceptionTime");
					this.OnExceptionTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stacktrace", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Stacktrace
		{
			get
			{
				return this._Stacktrace;
			}
			set
			{
				if ((this._Stacktrace != value))
				{
					this.OnStacktraceChanging(value);
					this.SendPropertyChanging();
					this._Stacktrace = value;
					this.SendPropertyChanged("Stacktrace");
					this.OnStacktraceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StacktraceHash", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string StacktraceHash
		{
			get
			{
				return this._StacktraceHash;
			}
			set
			{
				if ((this._StacktraceHash != value))
				{
					this.OnStacktraceHashChanging(value);
					this.SendPropertyChanging();
					this._StacktraceHash = value;
					this.SendPropertyChanged("StacktraceHash");
					this.OnStacktraceHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaultiveFunction", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FaultiveFunction
		{
			get
			{
				return this._FaultiveFunction;
			}
			set
			{
				if ((this._FaultiveFunction != value))
				{
					this.OnFaultiveFunctionChanging(value);
					this.SendPropertyChanging();
					this._FaultiveFunction = value;
					this.SendPropertyChanged("FaultiveFunction");
					this.OnFaultiveFunctionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionData", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ExceptionData
		{
			get
			{
				return this._ExceptionData;
			}
			set
			{
				if ((this._ExceptionData != value))
				{
					this.OnExceptionDataChanging(value);
					this.SendPropertyChanging();
					this._ExceptionData = value;
					this.SendPropertyChanged("ExceptionData");
					this.OnExceptionDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BuildNumber
		{
			get
			{
				return this._BuildNumber;
			}
			set
			{
				if ((this._BuildNumber != value))
				{
					this.OnBuildNumberChanging(value);
					this.SendPropertyChanging();
					this._BuildNumber = value;
					this.SendPropertyChanged("BuildNumber");
					this.OnBuildNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManagedServers")]
	public partial class ManagedServer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ManagedServerID;
		
		private string _ServerName;
		
		private string _Role;
		
		private string _PublicIP;
		
		private string _PrivateIP;
		
		private System.DateTime _NextPollTime;
		
		private bool _IsDisable;
		
		private string _ServerIDC;
		
		private int _Region;
		
		private string _City;
		
		private string _CPUModel;
		
		private decimal _CPUSpeed;
		
		private int _CPUs;
		
		private short _CPUCore;
		
		private System.Nullable<short> _DiskSpace;
		
		private int _RAM;
		
		private System.Nullable<int> _AllowedBandwidth;
		
		private string _Note;
		
		private System.Nullable<System.DateTime> _DeploymentTime;
		
		private System.Nullable<decimal> _Price;
		
		private EntitySet<ManagedServerMonitoring> _ManagedServerMonitorings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManagedServerIDChanging(int value);
    partial void OnManagedServerIDChanged();
    partial void OnServerNameChanging(string value);
    partial void OnServerNameChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnPublicIPChanging(string value);
    partial void OnPublicIPChanged();
    partial void OnPrivateIPChanging(string value);
    partial void OnPrivateIPChanged();
    partial void OnNextPollTimeChanging(System.DateTime value);
    partial void OnNextPollTimeChanged();
    partial void OnIsDisableChanging(bool value);
    partial void OnIsDisableChanged();
    partial void OnServerIDCChanging(string value);
    partial void OnServerIDCChanged();
    partial void OnRegionChanging(int value);
    partial void OnRegionChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnCPUModelChanging(string value);
    partial void OnCPUModelChanged();
    partial void OnCPUSpeedChanging(decimal value);
    partial void OnCPUSpeedChanged();
    partial void OnCPUsChanging(int value);
    partial void OnCPUsChanged();
    partial void OnCPUCoreChanging(short value);
    partial void OnCPUCoreChanged();
    partial void OnDiskSpaceChanging(System.Nullable<short> value);
    partial void OnDiskSpaceChanged();
    partial void OnRAMChanging(int value);
    partial void OnRAMChanged();
    partial void OnAllowedBandwidthChanging(System.Nullable<int> value);
    partial void OnAllowedBandwidthChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnDeploymentTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDeploymentTimeChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    #endregion
		
		public ManagedServer()
		{
			this._ManagedServerMonitorings = new EntitySet<ManagedServerMonitoring>(new Action<ManagedServerMonitoring>(this.attach_ManagedServerMonitorings), new Action<ManagedServerMonitoring>(this.detach_ManagedServerMonitorings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedServerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ManagedServerID
		{
			get
			{
				return this._ManagedServerID;
			}
			set
			{
				if ((this._ManagedServerID != value))
				{
					this.OnManagedServerIDChanging(value);
					this.SendPropertyChanging();
					this._ManagedServerID = value;
					this.SendPropertyChanged("ManagedServerID");
					this.OnManagedServerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerName", DbType="NVarChar(50)")]
		public string ServerName
		{
			get
			{
				return this._ServerName;
			}
			set
			{
				if ((this._ServerName != value))
				{
					this.OnServerNameChanging(value);
					this.SendPropertyChanging();
					this._ServerName = value;
					this.SendPropertyChanged("ServerName");
					this.OnServerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(250)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicIP", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PublicIP
		{
			get
			{
				return this._PublicIP;
			}
			set
			{
				if ((this._PublicIP != value))
				{
					this.OnPublicIPChanging(value);
					this.SendPropertyChanging();
					this._PublicIP = value;
					this.SendPropertyChanged("PublicIP");
					this.OnPublicIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrivateIP", DbType="VarChar(30)")]
		public string PrivateIP
		{
			get
			{
				return this._PrivateIP;
			}
			set
			{
				if ((this._PrivateIP != value))
				{
					this.OnPrivateIPChanging(value);
					this.SendPropertyChanging();
					this._PrivateIP = value;
					this.SendPropertyChanged("PrivateIP");
					this.OnPrivateIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextPollTime", DbType="DateTime NOT NULL")]
		public System.DateTime NextPollTime
		{
			get
			{
				return this._NextPollTime;
			}
			set
			{
				if ((this._NextPollTime != value))
				{
					this.OnNextPollTimeChanging(value);
					this.SendPropertyChanging();
					this._NextPollTime = value;
					this.SendPropertyChanged("NextPollTime");
					this.OnNextPollTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDisable", DbType="Bit NOT NULL")]
		public bool IsDisable
		{
			get
			{
				return this._IsDisable;
			}
			set
			{
				if ((this._IsDisable != value))
				{
					this.OnIsDisableChanging(value);
					this.SendPropertyChanging();
					this._IsDisable = value;
					this.SendPropertyChanged("IsDisable");
					this.OnIsDisableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerIDC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ServerIDC
		{
			get
			{
				return this._ServerIDC;
			}
			set
			{
				if ((this._ServerIDC != value))
				{
					this.OnServerIDCChanging(value);
					this.SendPropertyChanging();
					this._ServerIDC = value;
					this.SendPropertyChanged("ServerIDC");
					this.OnServerIDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="Int NOT NULL")]
		public int Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPUModel", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CPUModel
		{
			get
			{
				return this._CPUModel;
			}
			set
			{
				if ((this._CPUModel != value))
				{
					this.OnCPUModelChanging(value);
					this.SendPropertyChanging();
					this._CPUModel = value;
					this.SendPropertyChanged("CPUModel");
					this.OnCPUModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPUSpeed", DbType="Decimal(18,2) NOT NULL")]
		public decimal CPUSpeed
		{
			get
			{
				return this._CPUSpeed;
			}
			set
			{
				if ((this._CPUSpeed != value))
				{
					this.OnCPUSpeedChanging(value);
					this.SendPropertyChanging();
					this._CPUSpeed = value;
					this.SendPropertyChanged("CPUSpeed");
					this.OnCPUSpeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPUs", DbType="Int NOT NULL")]
		public int CPUs
		{
			get
			{
				return this._CPUs;
			}
			set
			{
				if ((this._CPUs != value))
				{
					this.OnCPUsChanging(value);
					this.SendPropertyChanging();
					this._CPUs = value;
					this.SendPropertyChanged("CPUs");
					this.OnCPUsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPUCore", DbType="SmallInt NOT NULL")]
		public short CPUCore
		{
			get
			{
				return this._CPUCore;
			}
			set
			{
				if ((this._CPUCore != value))
				{
					this.OnCPUCoreChanging(value);
					this.SendPropertyChanging();
					this._CPUCore = value;
					this.SendPropertyChanged("CPUCore");
					this.OnCPUCoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiskSpace", DbType="SmallInt")]
		public System.Nullable<short> DiskSpace
		{
			get
			{
				return this._DiskSpace;
			}
			set
			{
				if ((this._DiskSpace != value))
				{
					this.OnDiskSpaceChanging(value);
					this.SendPropertyChanging();
					this._DiskSpace = value;
					this.SendPropertyChanged("DiskSpace");
					this.OnDiskSpaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAM", DbType="Int NOT NULL")]
		public int RAM
		{
			get
			{
				return this._RAM;
			}
			set
			{
				if ((this._RAM != value))
				{
					this.OnRAMChanging(value);
					this.SendPropertyChanging();
					this._RAM = value;
					this.SendPropertyChanged("RAM");
					this.OnRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowedBandwidth", DbType="Int")]
		public System.Nullable<int> AllowedBandwidth
		{
			get
			{
				return this._AllowedBandwidth;
			}
			set
			{
				if ((this._AllowedBandwidth != value))
				{
					this.OnAllowedBandwidthChanging(value);
					this.SendPropertyChanging();
					this._AllowedBandwidth = value;
					this.SendPropertyChanged("AllowedBandwidth");
					this.OnAllowedBandwidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(500)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeploymentTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeploymentTime
		{
			get
			{
				return this._DeploymentTime;
			}
			set
			{
				if ((this._DeploymentTime != value))
				{
					this.OnDeploymentTimeChanging(value);
					this.SendPropertyChanging();
					this._DeploymentTime = value;
					this.SendPropertyChanged("DeploymentTime");
					this.OnDeploymentTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManagedServer_ManagedServerMonitoring", Storage="_ManagedServerMonitorings", ThisKey="ManagedServerID", OtherKey="ManagedServerId")]
		public EntitySet<ManagedServerMonitoring> ManagedServerMonitorings
		{
			get
			{
				return this._ManagedServerMonitorings;
			}
			set
			{
				this._ManagedServerMonitorings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ManagedServerMonitorings(ManagedServerMonitoring entity)
		{
			this.SendPropertyChanging();
			entity.ManagedServer = this;
		}
		
		private void detach_ManagedServerMonitorings(ManagedServerMonitoring entity)
		{
			this.SendPropertyChanging();
			entity.ManagedServer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhotonMonitoringDetails")]
	public partial class PhotonMonitoringDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PhotonMonitoringDetailId;
		
		private int _CpuUtilization;
		
		private int _RamUtilization;
		
		private int _InstanceRamMb;
		
		private int _PeerCount;
		
		private System.DateTime _StatDate;
		
		private int _InstanceId;
		
		private EntityRef<PhotonMonitoringInstance> _PhotonMonitoringInstance;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPhotonMonitoringDetailIdChanging(int value);
    partial void OnPhotonMonitoringDetailIdChanged();
    partial void OnCpuUtilizationChanging(int value);
    partial void OnCpuUtilizationChanged();
    partial void OnRamUtilizationChanging(int value);
    partial void OnRamUtilizationChanged();
    partial void OnInstanceRamMbChanging(int value);
    partial void OnInstanceRamMbChanged();
    partial void OnPeerCountChanging(int value);
    partial void OnPeerCountChanged();
    partial void OnStatDateChanging(System.DateTime value);
    partial void OnStatDateChanged();
    partial void OnInstanceIdChanging(int value);
    partial void OnInstanceIdChanged();
    #endregion
		
		public PhotonMonitoringDetail()
		{
			this._PhotonMonitoringInstance = default(EntityRef<PhotonMonitoringInstance>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotonMonitoringDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PhotonMonitoringDetailId
		{
			get
			{
				return this._PhotonMonitoringDetailId;
			}
			set
			{
				if ((this._PhotonMonitoringDetailId != value))
				{
					this.OnPhotonMonitoringDetailIdChanging(value);
					this.SendPropertyChanging();
					this._PhotonMonitoringDetailId = value;
					this.SendPropertyChanged("PhotonMonitoringDetailId");
					this.OnPhotonMonitoringDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CpuUtilization", DbType="Int NOT NULL")]
		public int CpuUtilization
		{
			get
			{
				return this._CpuUtilization;
			}
			set
			{
				if ((this._CpuUtilization != value))
				{
					this.OnCpuUtilizationChanging(value);
					this.SendPropertyChanging();
					this._CpuUtilization = value;
					this.SendPropertyChanged("CpuUtilization");
					this.OnCpuUtilizationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RamUtilization", DbType="Int NOT NULL")]
		public int RamUtilization
		{
			get
			{
				return this._RamUtilization;
			}
			set
			{
				if ((this._RamUtilization != value))
				{
					this.OnRamUtilizationChanging(value);
					this.SendPropertyChanging();
					this._RamUtilization = value;
					this.SendPropertyChanged("RamUtilization");
					this.OnRamUtilizationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstanceRamMb", DbType="Int NOT NULL")]
		public int InstanceRamMb
		{
			get
			{
				return this._InstanceRamMb;
			}
			set
			{
				if ((this._InstanceRamMb != value))
				{
					this.OnInstanceRamMbChanging(value);
					this.SendPropertyChanging();
					this._InstanceRamMb = value;
					this.SendPropertyChanged("InstanceRamMb");
					this.OnInstanceRamMbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeerCount", DbType="Int NOT NULL")]
		public int PeerCount
		{
			get
			{
				return this._PeerCount;
			}
			set
			{
				if ((this._PeerCount != value))
				{
					this.OnPeerCountChanging(value);
					this.SendPropertyChanging();
					this._PeerCount = value;
					this.SendPropertyChanged("PeerCount");
					this.OnPeerCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatDate", DbType="DateTime NOT NULL")]
		public System.DateTime StatDate
		{
			get
			{
				return this._StatDate;
			}
			set
			{
				if ((this._StatDate != value))
				{
					this.OnStatDateChanging(value);
					this.SendPropertyChanging();
					this._StatDate = value;
					this.SendPropertyChanged("StatDate");
					this.OnStatDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstanceId", DbType="Int NOT NULL")]
		public int InstanceId
		{
			get
			{
				return this._InstanceId;
			}
			set
			{
				if ((this._InstanceId != value))
				{
					if (this._PhotonMonitoringInstance.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInstanceIdChanging(value);
					this.SendPropertyChanging();
					this._InstanceId = value;
					this.SendPropertyChanged("InstanceId");
					this.OnInstanceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhotonMonitoringInstance_PhotonMonitoringDetail", Storage="_PhotonMonitoringInstance", ThisKey="InstanceId", OtherKey="PhotonMonitoringInstanceId", IsForeignKey=true)]
		public PhotonMonitoringInstance PhotonMonitoringInstance
		{
			get
			{
				return this._PhotonMonitoringInstance.Entity;
			}
			set
			{
				PhotonMonitoringInstance previousValue = this._PhotonMonitoringInstance.Entity;
				if (((previousValue != value) 
							|| (this._PhotonMonitoringInstance.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhotonMonitoringInstance.Entity = null;
						previousValue.PhotonMonitoringDetails.Remove(this);
					}
					this._PhotonMonitoringInstance.Entity = value;
					if ((value != null))
					{
						value.PhotonMonitoringDetails.Add(this);
						this._InstanceId = value.PhotonMonitoringInstanceId;
					}
					else
					{
						this._InstanceId = default(int);
					}
					this.SendPropertyChanged("PhotonMonitoringInstance");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhotonMonitoringInstances")]
	public partial class PhotonMonitoringInstance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PhotonMonitoringInstanceId;
		
		private string _InstanceName;
		
		private string _VersionNumber;
		
		private long _InstanceIp;
		
		private int _InstancePort;
		
		private EntitySet<PhotonMonitoringDetail> _PhotonMonitoringDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPhotonMonitoringInstanceIdChanging(int value);
    partial void OnPhotonMonitoringInstanceIdChanged();
    partial void OnInstanceNameChanging(string value);
    partial void OnInstanceNameChanged();
    partial void OnVersionNumberChanging(string value);
    partial void OnVersionNumberChanged();
    partial void OnInstanceIpChanging(long value);
    partial void OnInstanceIpChanged();
    partial void OnInstancePortChanging(int value);
    partial void OnInstancePortChanged();
    #endregion
		
		public PhotonMonitoringInstance()
		{
			this._PhotonMonitoringDetails = new EntitySet<PhotonMonitoringDetail>(new Action<PhotonMonitoringDetail>(this.attach_PhotonMonitoringDetails), new Action<PhotonMonitoringDetail>(this.detach_PhotonMonitoringDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotonMonitoringInstanceId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PhotonMonitoringInstanceId
		{
			get
			{
				return this._PhotonMonitoringInstanceId;
			}
			set
			{
				if ((this._PhotonMonitoringInstanceId != value))
				{
					this.OnPhotonMonitoringInstanceIdChanging(value);
					this.SendPropertyChanging();
					this._PhotonMonitoringInstanceId = value;
					this.SendPropertyChanged("PhotonMonitoringInstanceId");
					this.OnPhotonMonitoringInstanceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstanceName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string InstanceName
		{
			get
			{
				return this._InstanceName;
			}
			set
			{
				if ((this._InstanceName != value))
				{
					this.OnInstanceNameChanging(value);
					this.SendPropertyChanging();
					this._InstanceName = value;
					this.SendPropertyChanged("InstanceName");
					this.OnInstanceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstanceIp", DbType="BigInt NOT NULL")]
		public long InstanceIp
		{
			get
			{
				return this._InstanceIp;
			}
			set
			{
				if ((this._InstanceIp != value))
				{
					this.OnInstanceIpChanging(value);
					this.SendPropertyChanging();
					this._InstanceIp = value;
					this.SendPropertyChanged("InstanceIp");
					this.OnInstanceIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstancePort", DbType="Int NOT NULL")]
		public int InstancePort
		{
			get
			{
				return this._InstancePort;
			}
			set
			{
				if ((this._InstancePort != value))
				{
					this.OnInstancePortChanging(value);
					this.SendPropertyChanging();
					this._InstancePort = value;
					this.SendPropertyChanged("InstancePort");
					this.OnInstancePortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhotonMonitoringInstance_PhotonMonitoringDetail", Storage="_PhotonMonitoringDetails", ThisKey="PhotonMonitoringInstanceId", OtherKey="InstanceId")]
		public EntitySet<PhotonMonitoringDetail> PhotonMonitoringDetails
		{
			get
			{
				return this._PhotonMonitoringDetails;
			}
			set
			{
				this._PhotonMonitoringDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhotonMonitoringDetails(PhotonMonitoringDetail entity)
		{
			this.SendPropertyChanging();
			entity.PhotonMonitoringInstance = this;
		}
		
		private void detach_PhotonMonitoringDetails(PhotonMonitoringDetail entity)
		{
			this.SendPropertyChanging();
			entity.PhotonMonitoringInstance = null;
		}
	}
}
#pragma warning restore 1591
