/////////////////////////////////////////////////
/// This file was autogenerated by a T4 template
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using System;
using System.IO;
using System.ServiceModel;
using System.ServiceModel.Web;
using Cmune.DataCenter.Utils;
using UberStrike.DataCenter.WebService.Crypto;
using UberStrike.Core.Serialization;
using UberStrike.DataCenter.WebService.Interfaces;
