/////////////////////////////////////////////////
/// This file was autogenerated by a T4 template
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using System.Collections.Generic;
using System.IO;
using Cmune.DataCenter.Common.Entities;
using Photon.SocketServer;
using PhotonHostRuntimeInterfaces;
using UberStrike.Realtime.Server;
using UberStrike.Core.Serialization;

namespace UberStrike.Realtime.GameServer
{
    public abstract class BaseDeathmatchRoom : BaseRoom
    {
        public DeathmatchEventFactory Events { get; private set; }

        protected BaseDeathmatchRoom(int roomId)
			: base(roomId)
        { 
			Events = new  DeathmatchEventFactory(this);
		}

		protected sealed override void OnOperation(byte operationId, ICmunePeer peer, byte[] data)
		{
			switch (operationId)
			{
				case 1: KillPlayer(peer, data); break;
				case 2: ShootPlayer(peer, data); break;
			}
		}
		
		protected abstract void OnKillPlayer(ICmunePeer peer, int killedPeerId);
		protected abstract void OnShootPlayer(ICmunePeer peer, int shotPeerId);

    	private void KillPlayer(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int killedPeerId = Int32Proxy.Deserialize(stream);
				OnKillPlayer(peer, killedPeerId);
			}
		}

    	private void ShootPlayer(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int shotPeerId = Int32Proxy.Deserialize(stream);
				OnShootPlayer(peer, shotPeerId);
			}
		}
	}

    public abstract class BaseGameServerPeer : BasePeer
    {
        public GameServerPeerEventFactory Events { get; private set; }

        protected BaseGameServerPeer(IRpcProtocol protocol, IPhotonPeer photonPeer, int cmuneId, ChannelType channel)
			: base(protocol, photonPeer, cmuneId, channel)
        {
			Events = new GameServerPeerEventFactory(this);
        }

		protected sealed override void OnOperation(byte operationId, byte[] data)
		{
			switch (operationId)
			{
				case 1: GetServerLoad(data); break;
				case 2: JoinGameRoom(data); break;
				case 3: CreateGameRoom(data); break;
				case 4: LeaveGameRoom(data); break;
				case 5: RegisterToGameLobby(data); break;
			}
		}
		
		protected abstract void OnGetServerLoad();
		protected abstract void OnJoinGameRoom(int roomId);
		protected abstract void OnCreateGameRoom(UberStrike.Core.Types.GameModeType type);
		protected abstract void OnLeaveGameRoom(int roomId);
		protected abstract void OnRegisterToGameLobby();

    	private void GetServerLoad(byte[] bytes)
        {
			using (var stream = new MemoryStream(bytes))
			{
				OnGetServerLoad();
			}
		}

    	private void JoinGameRoom(byte[] bytes)
        {
			using (var stream = new MemoryStream(bytes))
			{
        		int roomId = Int32Proxy.Deserialize(stream);
				OnJoinGameRoom(roomId);
			}
		}

    	private void CreateGameRoom(byte[] bytes)
        {
			using (var stream = new MemoryStream(bytes))
			{
        		UberStrike.Core.Types.GameModeType type = EnumProxy<UberStrike.Core.Types.GameModeType>.Deserialize(stream);
				OnCreateGameRoom(type);
			}
		}

    	private void LeaveGameRoom(byte[] bytes)
        {
			using (var stream = new MemoryStream(bytes))
			{
        		int roomId = Int32Proxy.Deserialize(stream);
				OnLeaveGameRoom(roomId);
			}
		}

    	private void RegisterToGameLobby(byte[] bytes)
        {
			using (var stream = new MemoryStream(bytes))
			{
				OnRegisterToGameLobby();
			}
		}
	}
	
    public sealed class DeathmatchEventFactory
    {
		private BaseRoom room;

		public DeathmatchEventFactory(BaseRoom room)
		{
			this.room = room;
		}

        public RoomEvent SendPlayerKilled(int playerId)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, playerId);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 1, Parameters = _data } );
			}
        }

        public RoomEvent SendPlayerShot(int playerId)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, playerId);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 2, Parameters = _data } );
			}
        }

	}
	
    public sealed class GameServerPeerEventFactory
    {
		private ICmunePeer peer;

		public GameServerPeerEventFactory(ICmunePeer peer)
		{
			this.peer = peer;
		}

        public void SendGameServerData(UberStrike.Core.ViewModel.ServerConnectionView data)
        {
            using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ServerConnectionViewProxy.Serialize(stream, data);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	peer.PublishEvent(new EventData() { Code = 1, Parameters = _data } );
			}
        }

        public void SendJoinedGameRoom(int roomId)
        {
            using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, roomId);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	peer.PublishEvent(new EventData() { Code = 2, Parameters = _data } );
			}
        }

        public void SendLeftGameRoom(int roomId)
        {
            using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, roomId);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	peer.PublishEvent(new EventData() { Code = 3, Parameters = _data } );
			}
        }

        public void SendFullGameList(System.Collections.Generic.List<int> gameList)
        {
            using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ListProxy<int>.Serialize(stream, gameList, Int32Proxy.Serialize);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	peer.PublishEvent(new EventData() { Code = 4, Parameters = _data } );
			}
        }

        public void SendGameListUpdate(System.Collections.Generic.Dictionary<int,int> updatedGames)
        {
            using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.DictionaryProxy<int,int>.Serialize(stream, updatedGames, Int32Proxy.Serialize, Int32Proxy.Serialize);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	peer.PublishEvent(new EventData() { Code = 5, Parameters = _data } );
			}
        }

        public void SendGamesDeleted(System.Collections.Generic.List<int> deletedGameIds)
        {
            using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ListProxy<int>.Serialize(stream, deletedGameIds, Int32Proxy.Serialize);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	peer.PublishEvent(new EventData() { Code = 6, Parameters = _data } );
			}
        }

	}
	
}