/////////////////////////////////////////////////
/// This file was autogenerated by a T4 template
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.IO;
using Cmune.Util;
using UberStrike.Core.Serialization;

namespace UberStrike.Realtime.Client
{
    public sealed class CommPeerOperations : IOperationSender
    {
		public event Func<byte, Dictionary<byte, object>, bool, bool> SendOperation;

		private byte _code = 0;

        public CommPeerOperations(byte opCode = 0)
        {
			_code = opCode;
        }

        public void SendGetServerLoad()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(1, _data, true);
			}
        }

        public void SendEnterLobby()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(2, _data, true);
			}
        }

        public void SendLeaveLobby()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(3, _data, true);
			}
        }

	}

    public sealed class LobbyRoomOperations : IOperationSender
    {
		public event Func<byte, Dictionary<byte, object>, bool, bool> SendOperation;

		private byte _code = 0;

        public LobbyRoomOperations(byte opCode = 0)
        {
			_code = opCode;
        }

        public void SendFullPlayerListUpdate()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(1, _data, true);
			}
        }

        public void SendUpdatePlayerRoom(UberStrike.Core.Models.CmuneRoomID room)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.CmuneRoomIDProxy.Serialize(stream, room);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(2, _data, true);
			}
        }

        public void SendResetPlayerRoom()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(3, _data, true);
			}
        }

        public void SendPlayerUpdate(UberStrike.Core.Models.CommActorInfo data)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.CommActorInfoProxy.Serialize(stream, data);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(4, _data, true);
			}
        }

        public void SendUpdateFriendsList(int cmid)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(5, _data, true);
			}
        }

        public void SendUpdateInboxMessages(int cmid, int messageId)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, messageId);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(6, _data, true);
			}
        }

        public void SendUpdateClanMembers(System.Collections.Generic.List<int> clanMembers)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ListProxy<int>.Serialize(stream, clanMembers, Int32Proxy.Serialize);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(7, _data, true);
			}
        }

        public void SendUpdateClanData(int cmid)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(8, _data, true);
			}
        }

        public void SendGetPlayersWithMatchingName(string search)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, search);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(9, _data, true);
			}
        }

        public void SendChatMessageInGame(string message, byte context)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				UberStrike.Core.Serialization.ByteProxy.Serialize(stream, context);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(10, _data, true);
			}
        }

        public void SendChatMessageToAll(string message)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(11, _data, true);
			}
        }

        public void SendChatMessageToPlayer(int cmid, string message)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(12, _data, true);
			}
        }

        public void SendModerationMutePlayer(int durationInMinutes, int cmid, bool disableChat)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, durationInMinutes);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.BooleanProxy.Serialize(stream, disableChat);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(13, _data, true);
			}
        }

        public void SendModerationPermanentBan(int cmid)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(14, _data, true);
			}
        }

        public void SendModerationBanPlayer(int cmid)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(15, _data, true);
			}
        }

        public void SendModerationKickGame(int cmid)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(16, _data, true);
			}
        }

        public void SendModerationUnbanPlayer(int cmid)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(17, _data, true);
			}
        }

        public void SendSpeedhackDetection()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(18, _data, true);
			}
        }

        public void SendSpeedhackDetectionNew(System.Collections.Generic.List<float> timeDifferences)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ListProxy<float>.Serialize(stream, timeDifferences, SingleProxy.Serialize);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(19, _data, true);
			}
        }

        public void SendPlayersReported(System.Collections.Generic.List<int> cmids, int type, string details, string logs)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ListProxy<int>.Serialize(stream, cmids, Int32Proxy.Serialize);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, type);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, details);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, logs);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(20, _data, true);
			}
        }

        public void SendSendNaughtyList()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(21, _data, true);
			}
        }

        public void SendClearModeratorFlags(int cmid)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(22, _data, true);
			}
        }

        public void SendSetContactList(System.Collections.Generic.List<int> cmids)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ListProxy<int>.Serialize(stream, cmids, Int32Proxy.Serialize);
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(23, _data, true);
			}
        }

        public void SendUpdateAllActors()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(24, _data, true);
			}
        }

        public void SendUpdateContacts()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ _code, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(25, _data, true);
			}
        }

	}

    public abstract class BaseCommPeer : BasePeer, IEventDispatcher
    {
		public CommPeerOperations Operations { get; private set; }

        protected BaseCommPeer(int syncFrequency) 
			: base(syncFrequency)
		{ 
			Operations = new CommPeerOperations(1);

            AddRoomLogic(this, Operations);
		}

		public void OnEvent(byte id, byte[] data)
        {
            switch (id)
			{
				case 1: LoadData(data); break;
				case 2: LobbyEntered(data); break;
            }
        }
	
		protected abstract void OnLoadData(UberStrike.Core.ViewModel.ServerConnectionView data);

		protected abstract void OnLobbyEntered();

    	private void LoadData(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		UberStrike.Core.ViewModel.ServerConnectionView data = ServerConnectionViewProxy.Deserialize(stream);
            	OnLoadData(data);
			}
        }
		
    	private void LobbyEntered(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
            	OnLobbyEntered();
			}
        }
		
	}
	
	public abstract class BaseLobbyRoom : IRoomLogic
    {
		public LobbyRoomOperations Operations { get; private set; }

        protected BaseLobbyRoom() 
		{ 
			Operations = new LobbyRoomOperations();
		}
		
        IOperationSender IRoomLogic.Operations
        {
            get { return Operations; }
        }

		public void OnEvent(byte id, byte[] data)
        {
            switch (id)
			{
				case 1: PlayerHide(data); break;
				case 2: PlayerLeft(data); break;
				case 3: PlayerUpdate(data); break;
				case 4: UpdateContacts(data); break;
				case 5: FullPlayerListUpdate(data); break;
				case 6: PlayerJoined(data); break;
				case 7: ClanChatMessage(data); break;
				case 8: InGameChatMessage(data); break;
				case 9: LobbyChatMessage(data); break;
				case 10: PrivateChatMessage(data); break;
				case 11: GameInviteMessage(data); break;
				case 12: DisconnectAndDisablePhoton(data); break;
				case 13: UpdateIngameGroup(data); break;
				case 14: UpdateInboxRequests(data); break;
				case 15: UpdateFriendsList(data); break;
				case 16: UpdateInboxMessages(data); break;
				case 17: UpdateClanMembers(data); break;
				case 18: UpdateClanData(data); break;
				case 19: UpdateActorsForModeration(data); break;
				case 20: ModerationCustomMessage(data); break;
				case 21: ModerationMutePlayer(data); break;
				case 22: ModerationKickGame(data); break;
            }
        }
	
		protected abstract void OnPlayerHide(int cmid);

		protected abstract void OnPlayerLeft(int cmid, bool refreshComm);

		protected abstract void OnPlayerUpdate(UberStrike.Core.Models.CommActorInfo data);

		protected abstract void OnUpdateContacts(System.Collections.Generic.List<UberStrike.Core.Models.CommActorInfo> updated, System.Collections.Generic.List<int> removed);

		protected abstract void OnFullPlayerListUpdate(System.Collections.Generic.List<UberStrike.Core.Models.CommActorInfo> players);

		protected abstract void OnPlayerJoined(UberStrike.Core.Models.CommActorInfo data);

		protected abstract void OnClanChatMessage(int cmid, string name, string message);

		protected abstract void OnInGameChatMessage(int cmid, string name, string message, Cmune.DataCenter.Common.Entities.MemberAccessLevel accessLevel, byte context);

		protected abstract void OnLobbyChatMessage(int cmid, string name, string message);

		protected abstract void OnPrivateChatMessage(int cmid, string name, string message);

		protected abstract void OnGameInviteMessage(int actorId, string message, UberStrike.Core.Models.CmuneRoomID roomId);

		protected abstract void OnDisconnectAndDisablePhoton(string message);

		protected abstract void OnUpdateIngameGroup(System.Collections.Generic.List<int> cmids);

		protected abstract void OnUpdateInboxRequests();

		protected abstract void OnUpdateFriendsList();

		protected abstract void OnUpdateInboxMessages(int messageId);

		protected abstract void OnUpdateClanMembers();

		protected abstract void OnUpdateClanData();

		protected abstract void OnUpdateActorsForModeration(System.Collections.Generic.List<UberStrike.Core.Models.CommActorInfo> allHackers);

		protected abstract void OnModerationCustomMessage(string message);

		protected abstract void OnModerationMutePlayer(bool isPlayerMuted);

		protected abstract void OnModerationKickGame();

    	private void PlayerHide(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
            	OnPlayerHide(cmid);
			}
        }
		
    	private void PlayerLeft(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
        		bool refreshComm = BooleanProxy.Deserialize(stream);
            	OnPlayerLeft(cmid, refreshComm);
			}
        }
		
    	private void PlayerUpdate(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		UberStrike.Core.Models.CommActorInfo data = CommActorInfoProxy.Deserialize(stream);
            	OnPlayerUpdate(data);
			}
        }
		
    	private void UpdateContacts(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		System.Collections.Generic.List<UberStrike.Core.Models.CommActorInfo> updated = ListProxy<UberStrike.Core.Models.CommActorInfo>.Deserialize(stream, CommActorInfoProxy.Deserialize);
        		System.Collections.Generic.List<int> removed = ListProxy<int>.Deserialize(stream, Int32Proxy.Deserialize);
            	OnUpdateContacts(updated, removed);
			}
        }
		
    	private void FullPlayerListUpdate(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		System.Collections.Generic.List<UberStrike.Core.Models.CommActorInfo> players = ListProxy<UberStrike.Core.Models.CommActorInfo>.Deserialize(stream, CommActorInfoProxy.Deserialize);
            	OnFullPlayerListUpdate(players);
			}
        }
		
    	private void PlayerJoined(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		UberStrike.Core.Models.CommActorInfo data = CommActorInfoProxy.Deserialize(stream);
            	OnPlayerJoined(data);
			}
        }
		
    	private void ClanChatMessage(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
        		string name = StringProxy.Deserialize(stream);
        		string message = StringProxy.Deserialize(stream);
            	OnClanChatMessage(cmid, name, message);
			}
        }
		
    	private void InGameChatMessage(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
        		string name = StringProxy.Deserialize(stream);
        		string message = StringProxy.Deserialize(stream);
        		Cmune.DataCenter.Common.Entities.MemberAccessLevel accessLevel = EnumProxy<Cmune.DataCenter.Common.Entities.MemberAccessLevel>.Deserialize(stream);
        		byte context = ByteProxy.Deserialize(stream);
            	OnInGameChatMessage(cmid, name, message, accessLevel, context);
			}
        }
		
    	private void LobbyChatMessage(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
        		string name = StringProxy.Deserialize(stream);
        		string message = StringProxy.Deserialize(stream);
            	OnLobbyChatMessage(cmid, name, message);
			}
        }
		
    	private void PrivateChatMessage(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
        		string name = StringProxy.Deserialize(stream);
        		string message = StringProxy.Deserialize(stream);
            	OnPrivateChatMessage(cmid, name, message);
			}
        }
		
    	private void GameInviteMessage(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int actorId = Int32Proxy.Deserialize(stream);
        		string message = StringProxy.Deserialize(stream);
        		UberStrike.Core.Models.CmuneRoomID roomId = CmuneRoomIDProxy.Deserialize(stream);
            	OnGameInviteMessage(actorId, message, roomId);
			}
        }
		
    	private void DisconnectAndDisablePhoton(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		string message = StringProxy.Deserialize(stream);
            	OnDisconnectAndDisablePhoton(message);
			}
        }
		
    	private void UpdateIngameGroup(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		System.Collections.Generic.List<int> cmids = ListProxy<int>.Deserialize(stream, Int32Proxy.Deserialize);
            	OnUpdateIngameGroup(cmids);
			}
        }
		
    	private void UpdateInboxRequests(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
            	OnUpdateInboxRequests();
			}
        }
		
    	private void UpdateFriendsList(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
            	OnUpdateFriendsList();
			}
        }
		
    	private void UpdateInboxMessages(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int messageId = Int32Proxy.Deserialize(stream);
            	OnUpdateInboxMessages(messageId);
			}
        }
		
    	private void UpdateClanMembers(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
            	OnUpdateClanMembers();
			}
        }
		
    	private void UpdateClanData(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
            	OnUpdateClanData();
			}
        }
		
    	private void UpdateActorsForModeration(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		System.Collections.Generic.List<UberStrike.Core.Models.CommActorInfo> allHackers = ListProxy<UberStrike.Core.Models.CommActorInfo>.Deserialize(stream, CommActorInfoProxy.Deserialize);
            	OnUpdateActorsForModeration(allHackers);
			}
        }
		
    	private void ModerationCustomMessage(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		string message = StringProxy.Deserialize(stream);
            	OnModerationCustomMessage(message);
			}
        }
		
    	private void ModerationMutePlayer(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		bool isPlayerMuted = BooleanProxy.Deserialize(stream);
            	OnModerationMutePlayer(isPlayerMuted);
			}
        }
		
    	private void ModerationKickGame(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
            	OnModerationKickGame();
			}
        }
		
	}
	
}