/////////////////////////////////////////////////
/// This file was autogenerated by a T4 template
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.IO;
using Cmune.Util;
using UberStrike.Core.Serialization;

namespace UberStrike.Realtime.Client
{
    public sealed class GameServerPeerOperations : IOperationSender
    {
		public event Func<byte, Dictionary<byte, object>, bool, bool> SendOperation;
		
        public GameServerPeerOperations()
        { }

        public void SendGetServerLoad()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(1, _data, true);
			}
        }

        public void SendJoinGameRoom(int roomId)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, roomId);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(2, _data, true);
			}
        }

        public void SendCreateGameRoom(UberStrike.Core.Types.GameModeType type)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.EnumProxy<UberStrike.Core.Types.GameModeType>.Serialize(stream, type);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(3, _data, true);
			}
        }

        public void SendLeaveGameRoom(int roomId)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, roomId);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(4, _data, true);
			}
        }

        public void SendRegisterToGameLobby()
        {
			using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(5, _data, true);
			}
        }

	}

    public sealed class DeathmatchOperations : IOperationSender
    {
		public event Func<byte, Dictionary<byte, object>, bool, bool> SendOperation;
		
        public DeathmatchOperations()
        { }

        public void SendKillPlayer(int killedPeerId)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, killedPeerId);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(1, _data, true);
			}
        }

        public void SendShootPlayer(int shotPeerId)
        {
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, shotPeerId);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				if(SendOperation != null) SendOperation(2, _data, true);
			}
        }

	}

    public abstract class BaseGameServerPeer : BasePeer, IEventDispatcher
    {
		public GameServerPeerOperations Operations { get; private set; }

        protected BaseGameServerPeer(int syncFrequency) 
			: base(syncFrequency)
		{ 
			Operations = new GameServerPeerOperations();

            AddRoomLogic(this, Operations);
		}

		public void OnEvent(byte id, byte[] data)
        {
            switch (id)
			{
				case 1: GameServerData(data); break;
				case 2: JoinedGameRoom(data); break;
				case 3: LeftGameRoom(data); break;
				case 4: FullGameList(data); break;
				case 5: GameListUpdate(data); break;
				case 6: GamesDeleted(data); break;
            }
        }
	
		protected abstract void OnGameServerData(UberStrike.Core.ViewModel.ServerConnectionView data);

		protected abstract void OnJoinedGameRoom(int roomId);

		protected abstract void OnLeftGameRoom(int roomId);

		protected abstract void OnFullGameList(System.Collections.Generic.List<int> gameList);

		protected abstract void OnGameListUpdate(System.Collections.Generic.Dictionary<int,int> updatedGames);

		protected abstract void OnGamesDeleted(System.Collections.Generic.List<int> deletedGameIds);

    	private void GameServerData(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		UberStrike.Core.ViewModel.ServerConnectionView data = ServerConnectionViewProxy.Deserialize(stream);
            	OnGameServerData(data);
			}
        }
		
    	private void JoinedGameRoom(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int roomId = Int32Proxy.Deserialize(stream);
            	OnJoinedGameRoom(roomId);
			}
        }
		
    	private void LeftGameRoom(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int roomId = Int32Proxy.Deserialize(stream);
            	OnLeftGameRoom(roomId);
			}
        }
		
    	private void FullGameList(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		System.Collections.Generic.List<int> gameList = ListProxy<int>.Deserialize(stream, Int32Proxy.Deserialize);
            	OnFullGameList(gameList);
			}
        }
		
    	private void GameListUpdate(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		System.Collections.Generic.Dictionary<int,int> updatedGames = DictionaryProxy<int,int>.Deserialize(stream, Int32Proxy.Deserialize, Int32Proxy.Deserialize);
            	OnGameListUpdate(updatedGames);
			}
        }
		
    	private void GamesDeleted(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		System.Collections.Generic.List<int> deletedGameIds = ListProxy<int>.Deserialize(stream, Int32Proxy.Deserialize);
            	OnGamesDeleted(deletedGameIds);
			}
        }
		
	}
	
	public abstract class BaseDeathmatch : IEventDispatcher
    {
		public DeathmatchOperations Operations { get; private set; }

        protected BaseDeathmatch() 
		{ 
			Operations = new DeathmatchOperations();
		}

		public void OnEvent(byte id, byte[] data)
        {
            switch (id)
			{
				case 1: PlayerKilled(data); break;
				case 2: PlayerShot(data); break;
            }
        }
	
		protected abstract void OnPlayerKilled(int playerId);

		protected abstract void OnPlayerShot(int playerId);

    	private void PlayerKilled(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int playerId = Int32Proxy.Deserialize(stream);
            	OnPlayerKilled(playerId);
			}
        }
		
    	private void PlayerShot(byte[] _bytes)
        {
			using(MemoryStream stream = new MemoryStream(_bytes))
			{
        		int playerId = Int32Proxy.Deserialize(stream);
            	OnPlayerShot(playerId);
			}
        }
		
	}
	
}