/////////////////////////////////////////////////
/// This file was autogenerated by a T4 template
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using System.Collections.Generic;
using System.IO;
using Cmune.DataCenter.Common.Entities;
using Photon.SocketServer;
using PhotonHostRuntimeInterfaces;
using UberStrike.Realtime.Server;
using UberStrike.Core.Serialization;

namespace UberStrike.Realtime.CommServer
{
    public abstract class BaseLobbyRoom : BaseRoom
    {
        public LobbyRoomEventFactory Events { get; private set; }

        protected BaseLobbyRoom(int roomId)
			: base(roomId)
        { 
			Events = new  LobbyRoomEventFactory(this);
		}

		protected sealed override void OnOperation(byte operationId, ICmunePeer peer, byte[] data)
		{
			switch (operationId)
			{
				case 1: FullPlayerListUpdate(peer, data); break;
				case 2: UpdatePlayerRoom(peer, data); break;
				case 3: ResetPlayerRoom(peer, data); break;
				case 4: PlayerUpdate(peer, data); break;
				case 5: UpdateFriendsList(peer, data); break;
				case 6: UpdateInboxMessages(peer, data); break;
				case 7: UpdateClanMembers(peer, data); break;
				case 8: UpdateClanData(peer, data); break;
				case 9: GetPlayersWithMatchingName(peer, data); break;
				case 10: ChatMessageInGame(peer, data); break;
				case 11: ChatMessageToAll(peer, data); break;
				case 12: ChatMessageToPlayer(peer, data); break;
				case 13: ModerationMutePlayer(peer, data); break;
				case 14: ModerationPermanentBan(peer, data); break;
				case 15: ModerationBanPlayer(peer, data); break;
				case 16: ModerationKickGame(peer, data); break;
				case 17: ModerationUnbanPlayer(peer, data); break;
				case 18: SpeedhackDetection(peer, data); break;
				case 19: SpeedhackDetectionNew(peer, data); break;
				case 20: PlayersReported(peer, data); break;
				case 21: SendNaughtyList(peer, data); break;
				case 22: ClearModeratorFlags(peer, data); break;
				case 23: SetContactList(peer, data); break;
				case 24: UpdateAllActors(peer, data); break;
				case 25: UpdateContacts(peer, data); break;
			}
		}
		
		protected abstract void OnFullPlayerListUpdate(ICmunePeer peer);
		protected abstract void OnUpdatePlayerRoom(ICmunePeer peer, UberStrike.Core.Models.CmuneRoomID room);
		protected abstract void OnResetPlayerRoom(ICmunePeer peer);
		protected abstract void OnPlayerUpdate(ICmunePeer peer, UberStrike.Core.Models.CommActorInfo data);
		protected abstract void OnUpdateFriendsList(ICmunePeer peer, int cmid);
		protected abstract void OnUpdateInboxMessages(ICmunePeer peer, int cmid, int messageId);
		protected abstract void OnUpdateClanMembers(ICmunePeer peer, System.Collections.Generic.List<int> clanMembers);
		protected abstract void OnUpdateClanData(ICmunePeer peer, int cmid);
		protected abstract void OnGetPlayersWithMatchingName(ICmunePeer peer, string search);
		protected abstract void OnChatMessageInGame(ICmunePeer peer, string message, byte context);
		protected abstract void OnChatMessageToAll(ICmunePeer peer, string message);
		protected abstract void OnChatMessageToPlayer(ICmunePeer peer, int cmid, string message);
		protected abstract void OnModerationMutePlayer(ICmunePeer peer, int durationInMinutes, int cmid, bool disableChat);
		protected abstract void OnModerationPermanentBan(ICmunePeer peer, int cmid);
		protected abstract void OnModerationBanPlayer(ICmunePeer peer, int cmid);
		protected abstract void OnModerationKickGame(ICmunePeer peer, int cmid);
		protected abstract void OnModerationUnbanPlayer(ICmunePeer peer, int cmid);
		protected abstract void OnSpeedhackDetection(ICmunePeer peer);
		protected abstract void OnSpeedhackDetectionNew(ICmunePeer peer, System.Collections.Generic.List<float> timeDifferences);
		protected abstract void OnPlayersReported(ICmunePeer peer, System.Collections.Generic.List<int> cmids, int type, string details, string logs);
		protected abstract void OnSendNaughtyList(ICmunePeer peer);
		protected abstract void OnClearModeratorFlags(ICmunePeer peer, int cmid);
		protected abstract void OnSetContactList(ICmunePeer peer, System.Collections.Generic.List<int> cmids);
		protected abstract void OnUpdateAllActors(ICmunePeer peer);
		protected abstract void OnUpdateContacts(ICmunePeer peer);

    	private void FullPlayerListUpdate(ICmunePeer peer, byte[] bytes)
        {
			OnFullPlayerListUpdate(peer);
		}

    	private void UpdatePlayerRoom(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		UberStrike.Core.Models.CmuneRoomID room = CmuneRoomIDProxy.Deserialize(stream);
				OnUpdatePlayerRoom(peer, room);
			}
		}

    	private void ResetPlayerRoom(ICmunePeer peer, byte[] bytes)
        {
			OnResetPlayerRoom(peer);
		}

    	private void PlayerUpdate(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		UberStrike.Core.Models.CommActorInfo data = CommActorInfoProxy.Deserialize(stream);
				OnPlayerUpdate(peer, data);
			}
		}

    	private void UpdateFriendsList(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
				OnUpdateFriendsList(peer, cmid);
			}
		}

    	private void UpdateInboxMessages(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
        		int messageId = Int32Proxy.Deserialize(stream);
				OnUpdateInboxMessages(peer, cmid, messageId);
			}
		}

    	private void UpdateClanMembers(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		System.Collections.Generic.List<int> clanMembers = ListProxy<int>.Deserialize(stream, Int32Proxy.Deserialize);
				OnUpdateClanMembers(peer, clanMembers);
			}
		}

    	private void UpdateClanData(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
				OnUpdateClanData(peer, cmid);
			}
		}

    	private void GetPlayersWithMatchingName(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		string search = StringProxy.Deserialize(stream);
				OnGetPlayersWithMatchingName(peer, search);
			}
		}

    	private void ChatMessageInGame(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		string message = StringProxy.Deserialize(stream);
        		byte context = ByteProxy.Deserialize(stream);
				OnChatMessageInGame(peer, message, context);
			}
		}

    	private void ChatMessageToAll(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		string message = StringProxy.Deserialize(stream);
				OnChatMessageToAll(peer, message);
			}
		}

    	private void ChatMessageToPlayer(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
        		string message = StringProxy.Deserialize(stream);
				OnChatMessageToPlayer(peer, cmid, message);
			}
		}

    	private void ModerationMutePlayer(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int durationInMinutes = Int32Proxy.Deserialize(stream);
        		int cmid = Int32Proxy.Deserialize(stream);
        		bool disableChat = BooleanProxy.Deserialize(stream);
				OnModerationMutePlayer(peer, durationInMinutes, cmid, disableChat);
			}
		}

    	private void ModerationPermanentBan(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
				OnModerationPermanentBan(peer, cmid);
			}
		}

    	private void ModerationBanPlayer(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
				OnModerationBanPlayer(peer, cmid);
			}
		}

    	private void ModerationKickGame(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
				OnModerationKickGame(peer, cmid);
			}
		}

    	private void ModerationUnbanPlayer(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
				OnModerationUnbanPlayer(peer, cmid);
			}
		}

    	private void SpeedhackDetection(ICmunePeer peer, byte[] bytes)
        {
			OnSpeedhackDetection(peer);
		}

    	private void SpeedhackDetectionNew(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		System.Collections.Generic.List<float> timeDifferences = ListProxy<float>.Deserialize(stream, SingleProxy.Deserialize);
				OnSpeedhackDetectionNew(peer, timeDifferences);
			}
		}

    	private void PlayersReported(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		System.Collections.Generic.List<int> cmids = ListProxy<int>.Deserialize(stream, Int32Proxy.Deserialize);
        		int type = Int32Proxy.Deserialize(stream);
        		string details = StringProxy.Deserialize(stream);
        		string logs = StringProxy.Deserialize(stream);
				OnPlayersReported(peer, cmids, type, details, logs);
			}
		}

    	private void SendNaughtyList(ICmunePeer peer, byte[] bytes)
        {
			OnSendNaughtyList(peer);
		}

    	private void ClearModeratorFlags(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		int cmid = Int32Proxy.Deserialize(stream);
				OnClearModeratorFlags(peer, cmid);
			}
		}

    	private void SetContactList(ICmunePeer peer, byte[] bytes)
        {
			using (MemoryStream stream = new MemoryStream(bytes))
			{
        		System.Collections.Generic.List<int> cmids = ListProxy<int>.Deserialize(stream, Int32Proxy.Deserialize);
				OnSetContactList(peer, cmids);
			}
		}

    	private void UpdateAllActors(ICmunePeer peer, byte[] bytes)
        {
			OnUpdateAllActors(peer);
		}

    	private void UpdateContacts(ICmunePeer peer, byte[] bytes)
        {
			OnUpdateContacts(peer);
		}
	}

    public abstract class BaseCommPeer : BasePeer
    {
        public CommPeerEventFactory Events { get; private set; }

        protected BaseCommPeer(IRpcProtocol protocol, IPhotonPeer photonPeer, int cmid, ChannelType channel)
			: base(protocol, photonPeer, cmid, channel)
        {
			Events = new CommPeerEventFactory(this);
        }

		protected sealed override void OnOperation(byte operationId, byte[] data)
		{
			switch (operationId)
			{
				case 1: GetServerLoad(data); break;
				case 2: EnterLobby(data); break;
				case 3: LeaveLobby(data); break;
			}
		}
		
		protected abstract void OnGetServerLoad();
		protected abstract void OnEnterLobby();
		protected abstract void OnLeaveLobby();

    	private void GetServerLoad(byte[] bytes)
        {
			OnGetServerLoad();
		}

    	private void EnterLobby(byte[] bytes)
        {
			OnEnterLobby();
		}

    	private void LeaveLobby(byte[] bytes)
        {
			OnLeaveLobby();
		}
	}
	
    public sealed class LobbyRoomEventFactory
    {
		private BaseRoom room;

		public LobbyRoomEventFactory(BaseRoom room)
		{
			this.room = room;
		}

        public RoomEvent SendPlayerHide(int cmid)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 1, Parameters = _data } );
			}
        }

        public RoomEvent SendPlayerLeft(int cmid, bool refreshComm)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.BooleanProxy.Serialize(stream, refreshComm);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 2, Parameters = _data } );
			}
        }

        public RoomEvent SendPlayerUpdate(UberStrike.Core.Models.CommActorInfo data)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.CommActorInfoProxy.Serialize(stream, data);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 3, Parameters = _data } );
			}
        }

        public RoomEvent SendUpdateContacts(System.Collections.Generic.List<UberStrike.Core.Models.CommActorInfo> updated, System.Collections.Generic.List<int> removed)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ListProxy<UberStrike.Core.Models.CommActorInfo>.Serialize(stream, updated, CommActorInfoProxy.Serialize);
				UberStrike.Core.Serialization.ListProxy<int>.Serialize(stream, removed, Int32Proxy.Serialize);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 4, Parameters = _data } );
			}
        }

        public RoomEvent SendFullPlayerListUpdate(System.Collections.Generic.List<UberStrike.Core.Models.CommActorInfo> players)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ListProxy<UberStrike.Core.Models.CommActorInfo>.Serialize(stream, players, CommActorInfoProxy.Serialize);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 5, Parameters = _data } );
			}
        }

        public RoomEvent SendPlayerJoined(UberStrike.Core.Models.CommActorInfo data)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.CommActorInfoProxy.Serialize(stream, data);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 6, Parameters = _data } );
			}
        }

        public RoomEvent SendClanChatMessage(int cmid, string name, string message)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, name);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 7, Parameters = _data } );
			}
        }

        public RoomEvent SendInGameChatMessage(int cmid, string name, string message, Cmune.DataCenter.Common.Entities.MemberAccessLevel accessLevel, byte context)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, name);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.MemberAccessLevel>.Serialize(stream, accessLevel);
				UberStrike.Core.Serialization.ByteProxy.Serialize(stream, context);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 8, Parameters = _data } );
			}
        }

        public RoomEvent SendLobbyChatMessage(int cmid, string name, string message)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, name);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 9, Parameters = _data } );
			}
        }

        public RoomEvent SendPrivateChatMessage(int cmid, string name, string message)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, name);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 10, Parameters = _data } );
			}
        }

        public RoomEvent SendGameInviteMessage(int actorId, string message, UberStrike.Core.Models.CmuneRoomID roomId)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, actorId);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				UberStrike.Core.Serialization.CmuneRoomIDProxy.Serialize(stream, roomId);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 11, Parameters = _data } );
			}
        }

        public RoomEvent SendDisconnectAndDisablePhoton(string message)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 12, Parameters = _data } );
			}
        }

        public RoomEvent SendUpdateIngameGroup(System.Collections.Generic.List<int> cmids)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ListProxy<int>.Serialize(stream, cmids, Int32Proxy.Serialize);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 13, Parameters = _data } );
			}
        }

        public RoomEvent SendUpdateInboxRequests()
        {
			using (var stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 14, Parameters = _data } );
			}
        }

        public RoomEvent SendUpdateFriendsList()
        {
			using (var stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 15, Parameters = _data } );
			}
        }

        public RoomEvent SendUpdateInboxMessages(int messageId)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, messageId);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 16, Parameters = _data } );
			}
        }

        public RoomEvent SendUpdateClanMembers()
        {
			using (var stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 17, Parameters = _data } );
			}
        }

        public RoomEvent SendUpdateClanData()
        {
			using (var stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 18, Parameters = _data } );
			}
        }

        public RoomEvent SendUpdateActorsForModeration(System.Collections.Generic.List<UberStrike.Core.Models.CommActorInfo> allHackers)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ListProxy<UberStrike.Core.Models.CommActorInfo>.Serialize(stream, allHackers, CommActorInfoProxy.Serialize);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 19, Parameters = _data } );
			}
        }

        public RoomEvent SendModerationCustomMessage(string message)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 20, Parameters = _data } );
			}
        }

        public RoomEvent SendModerationMutePlayer(bool isPlayerMuted)
        {
			using (var stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.BooleanProxy.Serialize(stream, isPlayerMuted);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 21, Parameters = _data } );
			}
        }

        public RoomEvent SendModerationKickGame()
        {
			using (var stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	return new RoomEvent(room, new EventData() { Code = 22, Parameters = _data } );
			}
        }

	}
	
    public sealed class CommPeerEventFactory
    {
		private ICmunePeer peer;

		public CommPeerEventFactory(ICmunePeer peer)
		{
			this.peer = peer;
		}

        public void SendLoadData(UberStrike.Core.ViewModel.ServerConnectionView data)
        {
            using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ServerConnectionViewProxy.Serialize(stream, data);
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	peer.PublishEvent(new EventData() { Code = 1, Parameters = _data } );
			}
        }

        public void SendLobbyEntered()
        {
            using(MemoryStream stream = new MemoryStream())
			{
				var _data = new Dictionary<byte, object>()
				{
					{ 0, stream.ToArray() }
				};
				
            	peer.PublishEvent(new EventData() { Code = 2, Parameters = _data } );
			}
        }

	}
	
}