/////////////////////////////////////////////////
/// This file was autogenerated by a T4 template
///
/// WARNING! All changes in this file will be lost!
/////////////////////////////////////////////////

using System.IO;
using Cmune.Core.Models.Views;
using UberStrike.Core.Serialization;
using UnityEngine;

namespace UberStrike.WebService.Unity
{
	#region IApplicationWebServiceContract
	
	public static class ApplicationWebServiceClient
	{
		[System.Obsolete("Replaced by AuthenticateApplication")]
		public static Coroutine RegisterClientApplication(int cmuneId, string hashCode, Cmune.DataCenter.Common.Entities.ChannelType channel, int applicationId, System.Action<UberStrike.Core.ViewModel.RegisterClientApplicationViewModel> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmuneId);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, hashCode);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channel);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"RegisterClientApplication",
					stream.ToArray(),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.RegisterClientApplicationViewModelProxy.Deserialize(new MemoryStream(data))); }, handler
				));
			}
		}
		
		[System.Obsolete("")]
		public static Coroutine GetPhotonServers(Cmune.DataCenter.Common.Entities.ApplicationView applicationView, System.Action<System.Collections.Generic.List<Cmune.Core.Models.Views.PhotonView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.ApplicationViewProxy.Serialize(stream, applicationView);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"GetPhotonServers",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.Core.Models.Views.PhotonView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), PhotonViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		[System.Obsolete("")]
		public static Coroutine GetMyIP(System.Action<string> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"GetMyIP",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.StringProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine AuthenticateApplication(string version, Cmune.DataCenter.Common.Entities.ChannelType channel, string publicKey, System.Action<UberStrike.DataCenter.Common.Entities.AuthenticateApplicationView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, version);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channel);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, publicKey);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"AuthenticateApplication",
					stream.ToArray(),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.AuthenticateApplicationViewProxy.Deserialize(new MemoryStream(data))); }, handler
				));
			}
		}
		
		public static Coroutine RecordException(int cmid, Cmune.DataCenter.Common.Entities.BuildType buildType, Cmune.DataCenter.Common.Entities.ChannelType channelType, string buildNumber, string logString, string stackTrace, string exceptionData, System.Action callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.BuildType>.Serialize(stream, buildType);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channelType);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, buildNumber);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, logString);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, stackTrace);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, exceptionData);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"RecordException",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(); }, handler
				));
			}
		}
		
		public static Coroutine RecordExceptionUnencrypted(Cmune.DataCenter.Common.Entities.BuildType buildType, Cmune.DataCenter.Common.Entities.ChannelType channelType, string buildNumber, string errorType, string errorMessage, System.Action callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.BuildType>.Serialize(stream, buildType);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channelType);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, buildNumber);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, errorType);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, errorMessage);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"RecordExceptionUnencrypted",
					stream.ToArray(),
					(data) => { if(callback != null) callback(); }, handler
				));
			}
		}
		
		public static Coroutine RecordTutorialStep(int cmid, UberStrike.Core.Types.TutorialStepType step, System.Action callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.EnumProxy<UberStrike.Core.Types.TutorialStepType>.Serialize(stream, step);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"RecordTutorialStep",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(); }, handler
				));
			}
		}
		
		public static Coroutine ReportBug(Cmune.DataCenter.Common.Entities.BugView bugView, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.BugViewProxy.Serialize(stream, bugView);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"ReportBug",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetLiveFeed(System.Action<System.Collections.Generic.List<UberStrike.DataCenter.Common.Entities.LiveFeedView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"GetLiveFeed",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<UberStrike.DataCenter.Common.Entities.LiveFeedView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), LiveFeedViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetMaps(string appVersion, UberStrike.Core.Types.LocaleType locale, UberStrike.Core.Types.MapType mapType, System.Action<System.Collections.Generic.List<UberStrike.Core.Models.Views.MapView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, appVersion);
				UberStrike.Core.Serialization.EnumProxy<UberStrike.Core.Types.LocaleType>.Serialize(stream, locale);
				UberStrike.Core.Serialization.EnumProxy<UberStrike.Core.Types.MapType>.Serialize(stream, mapType);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"GetMaps",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<UberStrike.Core.Models.Views.MapView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), MapViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine SetLevelVersion(int id, int version, string md5Hash, System.Action callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, id);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, version);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, md5Hash);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"SetLevelVersion",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(); }, handler
				));
			}
		}
		
		public static Coroutine GetPhotonServerName(string applicationVersion, string ipAddress, int port, System.Action<string> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, applicationVersion);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, ipAddress);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, port);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"GetPhotonServerName",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.StringProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine IsAlive(System.Action<string> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IApplicationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ApplicationWebServiceContract.svc",
					"IsAlive",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.StringProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
	}
	
	#endregion
	
	#region IAuthenticationWebServiceContract
	
	public static class AuthenticationWebServiceClient
	{
		public static Coroutine CreateUser(string emailAddress, string password, Cmune.DataCenter.Common.Entities.ChannelType channel, string locale, string machineId, System.Action<Cmune.DataCenter.Common.Entities.MemberRegistrationResult> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, emailAddress);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, password);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channel);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, locale);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, machineId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IAuthenticationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.AuthenticationWebServiceContract.svc",
					"CreateUser",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.MemberRegistrationResult>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine CompleteAccount(int cmid, string name, Cmune.DataCenter.Common.Entities.ChannelType channel, string locale, string machineId, System.Action<UberStrike.DataCenter.Common.Entities.AccountCompletionResultView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, name);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channel);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, locale);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, machineId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IAuthenticationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.AuthenticationWebServiceContract.svc",
					"CompleteAccount",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.AccountCompletionResultViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine UncompleteAccount(int cmid, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IAuthenticationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.AuthenticationWebServiceContract.svc",
					"UncompleteAccount",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine LoginMemberEmail(string email, string password, Cmune.DataCenter.Common.Entities.ChannelType channelType, string machineId, System.Action<UberStrike.Core.ViewModel.MemberAuthenticationResultView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, email);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, password);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channelType);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, machineId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IAuthenticationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.AuthenticationWebServiceContract.svc",
					"LoginMemberEmail",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.MemberAuthenticationResultViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine LoginMemberCookie(int cmid, System.DateTime expirationTime, string encryptedContent, string hash, Cmune.DataCenter.Common.Entities.ChannelType channelType, string machineId, System.Action<UberStrike.Core.ViewModel.MemberAuthenticationResultView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.DateTimeProxy.Serialize(stream, expirationTime);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, encryptedContent);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, hash);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channelType);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, machineId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IAuthenticationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.AuthenticationWebServiceContract.svc",
					"LoginMemberCookie",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.MemberAuthenticationResultViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
	}
	
	#endregion
	
	#region IClanWebServiceContract
	
	public static class ClanWebServiceClient
	{
		public static Coroutine IsMemberPartOfGroup(int cmuneId, int groupId, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmuneId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, groupId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"IsMemberPartOfGroup",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine IsMemberPartOfAnyGroup(int cmuneId, int applicationId, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmuneId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"IsMemberPartOfAnyGroup",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetClan(int groupId, System.Action<Cmune.DataCenter.Common.Entities.ClanView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, groupId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"GetClan",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ClanViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine UpdateMemberPosition(Cmune.DataCenter.Common.Entities.MemberPositionUpdateView updateMemberPositionData, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.MemberPositionUpdateViewProxy.Serialize(stream, updateMemberPositionData);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"UpdateMemberPosition",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine InviteMemberToJoinAGroup(int clanId, int inviterCmid, int inviteeCmid, string message, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, clanId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, inviterCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, inviteeCmid);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"InviteMemberToJoinAGroup",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine AcceptClanInvitation(int clanInvitationId, int cmid, System.Action<Cmune.DataCenter.Common.Entities.ClanRequestAcceptView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, clanInvitationId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"AcceptClanInvitation",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ClanRequestAcceptViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine DeclineClanInvitation(int clanInvitationId, int cmid, System.Action<Cmune.DataCenter.Common.Entities.ClanRequestDeclineView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, clanInvitationId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"DeclineClanInvitation",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ClanRequestDeclineViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine KickMemberFromClan(int groupId, int cmidTakingAction, int cmidToKick, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, groupId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmidTakingAction);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmidToKick);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"KickMemberFromClan",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine DisbandGroup(int groupId, int cmidTakingAction, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, groupId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmidTakingAction);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"DisbandGroup",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine LeaveAClan(int groupId, int cmid, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, groupId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"LeaveAClan",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetMyClanId(int cmid, int applicationId, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"GetMyClanId",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine CancelInvitation(int groupInvitationId, int cmid, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, groupInvitationId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"CancelInvitation",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine CancelRequest(int groupRequestId, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, groupRequestId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"CancelRequest",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetAllGroupInvitations(int inviteeCmid, int applicationId, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.GroupInvitationView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, inviteeCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"GetAllGroupInvitations",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.GroupInvitationView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), GroupInvitationViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetPendingGroupInvitations(int groupId, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.GroupInvitationView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, groupId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"GetPendingGroupInvitations",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.GroupInvitationView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), GroupInvitationViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine CreateClan(Cmune.DataCenter.Common.Entities.GroupCreationView createClanData, System.Action<Cmune.DataCenter.Common.Entities.ClanCreationReturnView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.GroupCreationViewProxy.Serialize(stream, createClanData);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"CreateClan",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ClanCreationReturnViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine TransferOwnership(int groupId, int previousLeaderCmid, int newLeaderCmid, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, groupId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, previousLeaderCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, newLeaderCmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"TransferOwnership",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine CanOwnAClan(int cmid, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"CanOwnAClan",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine test(System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IClanWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ClanWebServiceContract.svc",
					"test",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
	}
	
	#endregion
	
	#region IModerationWebServiceContract
	
	public static class ModerationWebServiceClient
	{
		public static Coroutine BanPermanently(int sourceCmid, int targetCmid, int applicationId, string ip, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, sourceCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, targetCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, ip);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IModerationWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ModerationWebServiceContract.svc",
					"BanPermanently",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
	}
	
	#endregion
	
	#region IPrivateMessageWebServiceContract
	
	public static class PrivateMessageWebServiceClient
	{
		[System.Obsolete("Please define a page number!")]
		public static Coroutine GetAllMessageThreadsForUser(int cmid, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.MessageThreadView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IPrivateMessageWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.PrivateMessageWebServiceContract.svc",
					"GetAllMessageThreadsForUser_1",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.MessageThreadView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), MessageThreadViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetAllMessageThreadsForUser(int cmid, int pageNumber, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.MessageThreadView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, pageNumber);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IPrivateMessageWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.PrivateMessageWebServiceContract.svc",
					"GetAllMessageThreadsForUser_2",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.MessageThreadView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), MessageThreadViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetThreadMessages(int threadViewerCmid, int otherCmid, int pageNumber, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.PrivateMessageView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, threadViewerCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, otherCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, pageNumber);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IPrivateMessageWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.PrivateMessageWebServiceContract.svc",
					"GetThreadMessages",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.PrivateMessageView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), PrivateMessageViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine SendMessage(int senderCmid, int receiverCmid, string content, System.Action<Cmune.DataCenter.Common.Entities.PrivateMessageView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, senderCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, receiverCmid);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, content);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IPrivateMessageWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.PrivateMessageWebServiceContract.svc",
					"SendMessage",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.PrivateMessageViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetMessageWithId(int messageId, int requesterCmid, System.Action<Cmune.DataCenter.Common.Entities.PrivateMessageView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, messageId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, requesterCmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IPrivateMessageWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.PrivateMessageWebServiceContract.svc",
					"GetMessageWithId",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.PrivateMessageViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine MarkThreadAsRead(int threadViewerCmid, int otherCmid, System.Action callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, threadViewerCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, otherCmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IPrivateMessageWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.PrivateMessageWebServiceContract.svc",
					"MarkThreadAsRead",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(); }, handler
				));
			}
		}
		
		public static Coroutine DeleteThread(int threadViewerCmid, int otherCmid, System.Action callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, threadViewerCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, otherCmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IPrivateMessageWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.PrivateMessageWebServiceContract.svc",
					"DeleteThread",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(); }, handler
				));
			}
		}
		
	}
	
	#endregion
	
	#region IRelationshipWebServiceContract
	
	public static class RelationshipWebServiceClient
	{
		public static Coroutine SendContactRequest(int initiatorCmid, int receiverCmid, string message, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, initiatorCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, receiverCmid);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, message);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IRelationshipWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.RelationshipWebServiceContract.svc",
					"SendContactRequest",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetContactRequests(int cmid, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.ContactRequestView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IRelationshipWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.RelationshipWebServiceContract.svc",
					"GetContactRequests",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.ContactRequestView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), ContactRequestViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine AcceptContactRequest(int contactRequestId, int cmid, int applicationId, System.Action<Cmune.DataCenter.Common.Entities.ContactRequestAcceptView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, contactRequestId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IRelationshipWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.RelationshipWebServiceContract.svc",
					"AcceptContactRequest",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ContactRequestAcceptViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine DeclineContactRequest(int contactRequestId, int cmid, System.Action<Cmune.DataCenter.Common.Entities.ContactRequestDeclineView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, contactRequestId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IRelationshipWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.RelationshipWebServiceContract.svc",
					"DeclineContactRequest",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ContactRequestDeclineViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine DeleteContact(int cmid, int contactCmid, System.Action<Cmune.DataCenter.Common.Entities.MemberOperationResult> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, contactCmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IRelationshipWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.RelationshipWebServiceContract.svc",
					"DeleteContact",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.MemberOperationResult>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine MoveContactToGroup(int cmid, int contactCmid, int previousGroupId, int newGroupId, System.Action<Cmune.DataCenter.Common.Entities.MemberOperationResult> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, contactCmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, previousGroupId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, newGroupId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IRelationshipWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.RelationshipWebServiceContract.svc",
					"MoveContactToGroup",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.MemberOperationResult>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetContactsByGroups(int cmid, int applicationId, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.ContactGroupView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IRelationshipWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.RelationshipWebServiceContract.svc",
					"GetContactsByGroups",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.ContactGroupView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), ContactGroupViewProxy.Deserialize)); }, handler
				));
			}
		}
		
	}
	
	#endregion
	
	#region IShopWebServiceContract
	
	public static class ShopWebServiceClient
	{
		public static Coroutine GetShop(string applicationVersion, System.Action<UberStrike.Core.Models.Views.UberStrikeItemShopClientView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, applicationVersion);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"GetShop",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.UberStrikeItemShopClientViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine BuyItem(int itemId, int buyerCmid, Cmune.DataCenter.Common.Entities.UberStrikeCurrencyType currencyType, Cmune.DataCenter.Common.Entities.BuyingDurationType durationType, UberStrike.Core.Types.UberstrikeItemType itemType, Cmune.DataCenter.Common.Entities.BuyingLocationType marketLocation, Cmune.DataCenter.Common.Entities.BuyingRecommendationType recommendationType, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, itemId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, buyerCmid);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.UberStrikeCurrencyType>.Serialize(stream, currencyType);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.BuyingDurationType>.Serialize(stream, durationType);
				UberStrike.Core.Serialization.EnumProxy<UberStrike.Core.Types.UberstrikeItemType>.Serialize(stream, itemType);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.BuyingLocationType>.Serialize(stream, marketLocation);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.BuyingRecommendationType>.Serialize(stream, recommendationType);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"BuyItem",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine BuyPack(int itemId, int buyerCmid, Cmune.DataCenter.Common.Entities.PackType packType, Cmune.DataCenter.Common.Entities.UberStrikeCurrencyType currencyType, UberStrike.Core.Types.UberstrikeItemType itemType, Cmune.DataCenter.Common.Entities.BuyingLocationType marketLocation, Cmune.DataCenter.Common.Entities.BuyingRecommendationType recommendationType, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, itemId);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, buyerCmid);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.PackType>.Serialize(stream, packType);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.UberStrikeCurrencyType>.Serialize(stream, currencyType);
				UberStrike.Core.Serialization.EnumProxy<UberStrike.Core.Types.UberstrikeItemType>.Serialize(stream, itemType);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.BuyingLocationType>.Serialize(stream, marketLocation);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.BuyingRecommendationType>.Serialize(stream, recommendationType);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"BuyPack",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetBundles(Cmune.DataCenter.Common.Entities.ChannelType channel, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.BundleView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channel);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"GetBundles",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.BundleView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), BundleViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine BuyMasBundle(int cmid, int bundleId, string hashedReceipt, int applicationId, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, bundleId);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, hashedReceipt);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"BuyMasBundle",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine BuyiPadBundle(int cmid, int bundleId, string hashedReceipt, int applicationId, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, bundleId);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, hashedReceipt);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"BuyiPadBundle",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine BuyiPhoneBundle(int cmid, int bundleId, string hashedReceipt, int applicationId, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, bundleId);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, hashedReceipt);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"BuyiPhoneBundle",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine UseConsumableItem(int cmid, int itemId, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, itemId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"UseConsumableItem",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetAllMysteryBoxs(System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.MysteryBoxUnityView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"GetAllMysteryBoxs_1",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.MysteryBoxUnityView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), MysteryBoxUnityViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetAllMysteryBoxs(Cmune.DataCenter.Common.Entities.BundleCategoryType bundleCategoryType, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.MysteryBoxUnityView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.BundleCategoryType>.Serialize(stream, bundleCategoryType);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"GetAllMysteryBoxs_2",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.MysteryBoxUnityView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), MysteryBoxUnityViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetMysteryBox(int mysteryBoxId, System.Action<Cmune.DataCenter.Common.Entities.MysteryBoxUnityView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, mysteryBoxId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"GetMysteryBox",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.MysteryBoxUnityViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine RollMysteryBox(int cmid, int mysteryBoxId, Cmune.DataCenter.Common.Entities.ChannelType channel, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.MysteryBoxWonItemUnityView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, mysteryBoxId);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channel);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"RollMysteryBox",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.MysteryBoxWonItemUnityView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), MysteryBoxWonItemUnityViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetAllLuckyDraws(System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.LuckyDrawUnityView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"GetAllLuckyDraws_1",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.LuckyDrawUnityView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), LuckyDrawUnityViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetAllLuckyDraws(Cmune.DataCenter.Common.Entities.BundleCategoryType bundleCategoryType, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.LuckyDrawUnityView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.BundleCategoryType>.Serialize(stream, bundleCategoryType);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"GetAllLuckyDraws_2",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.LuckyDrawUnityView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), LuckyDrawUnityViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetLuckyDraw(int luckyDrawId, System.Action<Cmune.DataCenter.Common.Entities.LuckyDrawUnityView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, luckyDrawId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"GetLuckyDraw",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.LuckyDrawUnityViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine RollLuckyDraw(int cmid, int luckDrawId, Cmune.DataCenter.Common.Entities.ChannelType channel, System.Action<int> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, luckDrawId);
				UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.ChannelType>.Serialize(stream, channel);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IShopWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.ShopWebServiceContract.svc",
					"RollLuckyDraw",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.Int32Proxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
	}
	
	#endregion
	
	#region IUserWebServiceContract
	
	public static class UserWebServiceClient
	{
		public static Coroutine ChangeMemberName(int cmid, string name, string locale, string machineId, System.Action<Cmune.DataCenter.Common.Entities.MemberOperationResult> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, name);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, locale);
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, machineId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"ChangeMemberName",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.MemberOperationResult>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine IsDuplicateMemberName(string username, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, username);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"IsDuplicateMemberName",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GenerateNonDuplicatedMemberNames(string username, System.Action<System.Collections.Generic.List<string>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, username);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GenerateNonDuplicatedMemberNames",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<string>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), StringProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetPublicProfile(int cmid, int applicationId, System.Action<Cmune.DataCenter.Common.Entities.PublicProfileView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, applicationId);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetPublicProfile",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.PublicProfileViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetMemberWallet(int cmid, System.Action<Cmune.DataCenter.Common.Entities.MemberWalletView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetMemberWallet",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.MemberWalletViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetInventory(int cmid, System.Action<System.Collections.Generic.List<Cmune.DataCenter.Common.Entities.ItemInventoryView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetInventory",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<Cmune.DataCenter.Common.Entities.ItemInventoryView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), ItemInventoryViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine ReportMember(Cmune.DataCenter.Common.Entities.MemberReportView memberReport, System.Action<bool> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.MemberReportViewProxy.Serialize(stream, memberReport);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"ReportMember",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.BooleanProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine FindMembers(string name, int maxResults, System.Action<System.Collections.Generic.Dictionary<int,string>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.StringProxy.Serialize(stream, name);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, maxResults);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"FindMembers",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.DictionaryProxy<int,string>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), Int32Proxy.Deserialize, StringProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetCurrencyDeposits(int cmid, int pageIndex, int elementPerPage, System.Action<UberStrike.Core.ViewModel.CurrencyDepositsViewModel> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, pageIndex);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, elementPerPage);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetCurrencyDeposits",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.CurrencyDepositsViewModelProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetItemTransactions(int cmid, int pageIndex, int elementPerPage, System.Action<UberStrike.Core.ViewModel.ItemTransactionsViewModel> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, pageIndex);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, elementPerPage);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetItemTransactions",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ItemTransactionsViewModelProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetPointsDeposits(int cmid, int pageIndex, int elementPerPage, System.Action<UberStrike.Core.ViewModel.PointDepositsViewModel> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, pageIndex);
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, elementPerPage);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetPointsDeposits",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.PointDepositsViewModelProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetUserAndTopStats(int cmid, System.Action<System.Collections.Generic.List<UberStrike.DataCenter.Common.Entities.PlayerCardView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetUserAndTopStats",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<UberStrike.DataCenter.Common.Entities.PlayerCardView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), PlayerCardViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetRealTimeStatistics(int cmid, System.Action<UberStrike.DataCenter.Common.Entities.PlayerCardView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetRealTimeStatistics",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.PlayerCardViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine SetScore(UberStrike.DataCenter.Common.Entities.MatchView scoringView, System.Action callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.MatchViewProxy.Serialize(stream, scoringView);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"SetScore",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(); }, handler
				));
			}
		}
		
		public static Coroutine GetMember(int cmid, System.Action<UberStrike.Core.ViewModel.UberstrikeUserViewModel> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetMember",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.UberstrikeUserViewModelProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetStatistics(int cmid, System.Action<UberStrike.DataCenter.Common.Entities.PlayerCardView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetStatistics",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.PlayerCardViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetLoadout(int cmid, System.Action<UberStrike.DataCenter.Common.Entities.LoadoutView> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.Int32Proxy.Serialize(stream, cmid);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetLoadout",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.LoadoutViewProxy.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine SetLoadout(UberStrike.DataCenter.Common.Entities.LoadoutView loadoutView, System.Action<Cmune.DataCenter.Common.Entities.MemberOperationResult> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				UberStrike.Core.Serialization.LoadoutViewProxy.Serialize(stream, loadoutView);
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"SetLoadout",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.EnumProxy<Cmune.DataCenter.Common.Entities.MemberOperationResult>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)))); }, handler
				));
			}
		}
		
		public static Coroutine GetXPEventsView(System.Action<System.Collections.Generic.Dictionary<int,UberStrike.DataCenter.Common.Entities.PlayerXPEventView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetXPEventsView",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.DictionaryProxy<int,UberStrike.DataCenter.Common.Entities.PlayerXPEventView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), Int32Proxy.Deserialize, PlayerXPEventViewProxy.Deserialize)); }, handler
				));
			}
		}
		
		public static Coroutine GetLevelCapsView(System.Action<System.Collections.Generic.List<UberStrike.DataCenter.Common.Entities.PlayerLevelCapView>> callback, System.Action<System.Exception> handler)
		{
			using(MemoryStream stream = new MemoryStream())
			{
				return WebServiceStarter.Mono.StartCoroutine(SoapClient.MakeRequest(
					"IUserWebServiceContract",
					"UberStrike.DataCenter.WebService.CWS.UserWebServiceContract.svc",
					"GetLevelCapsView",
					Cmune.Util.Cryptography.RijndaelEncrypt(stream.ToArray(), Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector),
					(data) => { if(callback != null) callback(UberStrike.Core.Serialization.ListProxy<UberStrike.DataCenter.Common.Entities.PlayerLevelCapView>.Deserialize(new MemoryStream(Cmune.Util.Cryptography.RijndaelDecrypt(data, Configuration.EncryptionPassPhrase, Configuration.EncryptionInitVector)), PlayerLevelCapViewProxy.Deserialize)); }, handler
				));
			}
		}
		
	}
	
	#endregion
	
}